#ifndef GUARD_CONSTANTS_TRAINERS_H
#define GUARD_CONSTANTS_TRAINERS_H

#include "constants/opponents.h"

#define TRAINER_ENCOUNTER_MUSIC_MALE         0 // standard male encounter music
#define TRAINER_ENCOUNTER_MUSIC_FEMALE       1 // standard female encounter music
#define TRAINER_ENCOUNTER_MUSIC_GIRL         2 // used for male Tubers and Young Couples too
#define TRAINER_ENCOUNTER_MUSIC_SUSPICIOUS   3
#define TRAINER_ENCOUNTER_MUSIC_INTENSE      4
#define TRAINER_ENCOUNTER_MUSIC_COOL         5
#define TRAINER_ENCOUNTER_MUSIC_AQUA         6
#define TRAINER_ENCOUNTER_MUSIC_MAGMA        7
#define TRAINER_ENCOUNTER_MUSIC_SWIMMER      8
#define TRAINER_ENCOUNTER_MUSIC_TWINS        9 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_ELITE_FOUR  10
#define TRAINER_ENCOUNTER_MUSIC_HIKER       11 // used for other trainer classes too
#define TRAINER_ENCOUNTER_MUSIC_INTERVIEWER 12
#define TRAINER_ENCOUNTER_MUSIC_RICH        13 // Rich Boys and Gentlemen

#define TRAINER_PIC_AQUA_LEADER_ARCHIE      0
#define TRAINER_PIC_AQUA_GRUNT_M            1
#define TRAINER_PIC_AQUA_GRUNT_F            2
#define TRAINER_PIC_RS_AROMA_LADY           3
#define TRAINER_PIC_RS_RUIN_MANIAC          4
#define TRAINER_PIC_INTERVIEWER             5
#define TRAINER_PIC_RS_TUBER_F              6
#define TRAINER_PIC_RS_TUBER_M              7
#define TRAINER_PIC_RS_COOLTRAINER_M        8
#define TRAINER_PIC_RS_COOLTRAINER_F        9
#define TRAINER_PIC_HEX_MANIAC             10
#define TRAINER_PIC_RS_LADY                11
#define TRAINER_PIC_RS_BEAUTY              12
#define TRAINER_PIC_RICH_BOY               13
#define TRAINER_PIC_RS_POKEMANIAC          14
#define TRAINER_PIC_RS_SWIMMER_M           15
#define TRAINER_PIC_RS_BLACK_BELT          16
#define TRAINER_PIC_GUITARIST              17
#define TRAINER_PIC_KINDLER                18
#define TRAINER_PIC_RS_CAMPER              19
#define TRAINER_PIC_BUG_MANIAC             20
#define TRAINER_PIC_RS_PSYCHIC_M           21
#define TRAINER_PIC_RS_PSYCHIC_F           22
#define TRAINER_PIC_RS_GENTLEMAN           23
#define TRAINER_PIC_ELITE_FOUR_SIDNEY      24
#define TRAINER_PIC_ELITE_FOUR_PHOEBE      25
#define TRAINER_PIC_LEADER_ROXANNE         26
#define TRAINER_PIC_LEADER_BRAWLY          27
#define TRAINER_PIC_LEADER_TATE_AND_LIZA   28
#define TRAINER_PIC_SCHOOL_KID_M           29
#define TRAINER_PIC_SCHOOL_KID_F           30
#define TRAINER_PIC_SR_AND_JR              31
#define TRAINER_PIC_POKEFAN_M              32
#define TRAINER_PIC_POKEFAN_F              33
#define TRAINER_PIC_EXPERT_M               34
#define TRAINER_PIC_EXPERT_F               35
#define TRAINER_PIC_RS_YOUNGSTER           36
#define TRAINER_PIC_CHAMPION_STEVEN        37
#define TRAINER_PIC_RS_FISHERMAN           38
#define TRAINER_PIC_CYCLING_TRIATHLETE_M   39
#define TRAINER_PIC_CYCLING_TRIATHLETE_F   40
#define TRAINER_PIC_RUNNING_TRIATHLETE_M   41
#define TRAINER_PIC_RUNNING_TRIATHLETE_F   42
#define TRAINER_PIC_SWIMMING_TRIATHLETE_M  43
#define TRAINER_PIC_SWIMMING_TRIATHLETE_F  44
#define TRAINER_PIC_DRAGON_TAMER           45
#define TRAINER_PIC_RS_BIRD_KEEPER         46
#define TRAINER_PIC_NINJA_BOY              47
#define TRAINER_PIC_BATTLE_GIRL            48
#define TRAINER_PIC_PARASOL_LADY           49
#define TRAINER_PIC_RS_SWIMMER_F           50
#define TRAINER_PIC_RS_PICNICKER           51
#define TRAINER_PIC_RS_TWINS               52
#define TRAINER_PIC_RS_SAILOR              53
#define TRAINER_PIC_COLLECTOR              54
#define TRAINER_PIC_WALLY                  55
#define TRAINER_PIC_RS_BRENDAN_1           56
#define TRAINER_PIC_RS_MAY_1               57
#define TRAINER_PIC_RS_POKEMON_BREEDER_M   58
#define TRAINER_PIC_RS_POKEMON_BREEDER_F   59
#define TRAINER_PIC_RS_POKEMON_RANGER_M    60
#define TRAINER_PIC_RS_POKEMON_RANGER_F    61
#define TRAINER_PIC_MAGMA_LEADER_MAXIE     62
#define TRAINER_PIC_MAGMA_GRUNT_M          63
#define TRAINER_PIC_MAGMA_GRUNT_F          64
#define TRAINER_PIC_RS_LASS                65
#define TRAINER_PIC_RS_BUG_CATCHER         66
#define TRAINER_PIC_RS_HIKER               67
#define TRAINER_PIC_RS_YOUNG_COUPLE        68
#define TRAINER_PIC_OLD_COUPLE             69
#define TRAINER_PIC_RS_SIS_AND_BRO         70
#define TRAINER_PIC_AQUA_ADMIN_M           71
#define TRAINER_PIC_AQUA_ADMIN_F           72
#define TRAINER_PIC_MAGMA_ADMIN_M          73
#define TRAINER_PIC_MAGMA_ADMIN_F          74
#define TRAINER_PIC_LEADER_WATTSON         75
#define TRAINER_PIC_LEADER_FLANNERY        76
#define TRAINER_PIC_LEADER_NORMAN          77
#define TRAINER_PIC_LEADER_WINONA          78
#define TRAINER_PIC_LEADER_WALLACE         79
#define TRAINER_PIC_ELITE_FOUR_GLACIA      80
#define TRAINER_PIC_ELITE_FOUR_DRAKE       81
#define TRAINER_PIC_YOUNGSTER              82
#define TRAINER_PIC_BUG_CATCHER            83
#define TRAINER_PIC_LASS                   84
#define TRAINER_PIC_SAILOR                 85
#define TRAINER_PIC_CAMPER                 86
#define TRAINER_PIC_PICNICKER              87
#define TRAINER_PIC_POKEMANIAC             88
#define TRAINER_PIC_SUPER_NERD             89
#define TRAINER_PIC_HIKER                  90
#define TRAINER_PIC_BIKER                  91
#define TRAINER_PIC_BURGLAR                92
#define TRAINER_PIC_ENGINEER               93
#define TRAINER_PIC_FISHERMAN              94
#define TRAINER_PIC_SWIMMER_M              95
#define TRAINER_PIC_CUE_BALL               96
#define TRAINER_PIC_GAMER                  97
#define TRAINER_PIC_BEAUTY                 98
#define TRAINER_PIC_SWIMMER_F              99
#define TRAINER_PIC_PSYCHIC_M             100
#define TRAINER_PIC_ROCKER                101
#define TRAINER_PIC_JUGGLER               102
#define TRAINER_PIC_TAMER                 103
#define TRAINER_PIC_BIRD_KEEPER           104
#define TRAINER_PIC_BLACK_BELT            105
#define TRAINER_PIC_RIVAL_EARLY           106
#define TRAINER_PIC_SCIENTIST             107
#define TRAINER_PIC_LEADER_GIOVANNI       108
#define TRAINER_PIC_ROCKET_GRUNT_M        109
#define TRAINER_PIC_COOLTRAINER_M         110
#define TRAINER_PIC_COOLTRAINER_F         111
#define TRAINER_PIC_ELITE_FOUR_LORELEI    112
#define TRAINER_PIC_ELITE_FOUR_BRUNO      113
#define TRAINER_PIC_ELITE_FOUR_AGATHA     114
#define TRAINER_PIC_ELITE_FOUR_LANCE      115
#define TRAINER_PIC_LEADER_BROCK          116
#define TRAINER_PIC_LEADER_MISTY          117
#define TRAINER_PIC_LEADER_LT_SURGE       118
#define TRAINER_PIC_LEADER_ERIKA          119
#define TRAINER_PIC_LEADER_KOGA           120
#define TRAINER_PIC_LEADER_BLAINE         121
#define TRAINER_PIC_LEADER_SABRINA        122
#define TRAINER_PIC_GENTLEMAN             123
#define TRAINER_PIC_RIVAL_LATE            124
#define TRAINER_PIC_CHAMPION_RIVAL        125
#define TRAINER_PIC_CHANNELER             126
#define TRAINER_PIC_TWINS                 127
#define TRAINER_PIC_COOL_COUPLE           128
#define TRAINER_PIC_YOUNG_COUPLE          129
#define TRAINER_PIC_CRUSH_KIN             130
#define TRAINER_PIC_SIS_AND_BRO           131
#define TRAINER_PIC_PROFESSOR_OAK         132
#define TRAINER_PIC_RS_BRENDAN_2          133
#define TRAINER_PIC_RS_MAY_2              134
#define TRAINER_PIC_RED                   135
#define TRAINER_PIC_LEAF                  136
#define TRAINER_PIC_ROCKET_GRUNT_F        137
#define TRAINER_PIC_PSYCHIC_F             138
#define TRAINER_PIC_CRUSH_GIRL            139
#define TRAINER_PIC_TUBER_F               140
#define TRAINER_PIC_POKEMON_BREEDER       141
#define TRAINER_PIC_POKEMON_RANGER_M      142
#define TRAINER_PIC_POKEMON_RANGER_F      143
#define TRAINER_PIC_AROMA_LADY            144
#define TRAINER_PIC_RUIN_MANIAC           145
#define TRAINER_PIC_LADY                  146
#define TRAINER_PIC_PAINTER               147
#define TRAINER_PIC_NEW_AARON               148
#define TRAINER_PIC_NEW_ACEROLA_MASTERS               149
#define TRAINER_PIC_NEW_ACEROLA               150
#define TRAINER_PIC_NEW_ACETRAINER_GEN1               151
#define TRAINER_PIC_NEW_ACETRAINER_GEN1RB               152
#define TRAINER_PIC_NEW_ACETRAINER_GEN2               153
#define TRAINER_PIC_NEW_ACETRAINER_GEN3               154
#define TRAINER_PIC_NEW_ACETRAINER_GEN3JP               155
#define TRAINER_PIC_NEW_ACETRAINER_GEN3RS               156
#define TRAINER_PIC_NEW_ACETRAINER_GEN4               157
#define TRAINER_PIC_NEW_ACETRAINER_GEN4DP               158
#define TRAINER_PIC_NEW_ACETRAINER_GEN6               159
#define TRAINER_PIC_NEW_ACETRAINER_GEN6XY               160
#define TRAINER_PIC_NEW_ACETRAINER_GEN7               161
#define TRAINER_PIC_NEW_ACETRAINER               162
#define TRAINER_PIC_NEW_ACETRAINERCOUPLE_GEN3               163
#define TRAINER_PIC_NEW_ACETRAINERCOUPLE               164
#define TRAINER_PIC_NEW_ACETRAINERF_GEN1               165
#define TRAINER_PIC_NEW_ACETRAINERF_GEN1RB               166
#define TRAINER_PIC_NEW_ACETRAINERF_GEN2               167
#define TRAINER_PIC_NEW_ACETRAINERF_GEN3               168
#define TRAINER_PIC_NEW_ACETRAINERF_GEN3RS               169
#define TRAINER_PIC_NEW_ACETRAINERF_GEN4               170
#define TRAINER_PIC_NEW_ACETRAINERF_GEN4DP               171
#define TRAINER_PIC_NEW_ACETRAINERF_GEN6               172
#define TRAINER_PIC_NEW_ACETRAINERF_GEN6XY               173
#define TRAINER_PIC_NEW_ACETRAINERF_GEN7               174
#define TRAINER_PIC_NEW_ACETRAINERF               175
#define TRAINER_PIC_NEW_ACETRAINERSNOW               176
#define TRAINER_PIC_NEW_ACETRAINERSNOWF               177
#define TRAINER_PIC_NEW_ADAMAN               178
#define TRAINER_PIC_NEW_AETHEREMPLOYEE               179
#define TRAINER_PIC_NEW_AETHEREMPLOYEEF               180
#define TRAINER_PIC_NEW_AETHERFOUNDATION               181
#define TRAINER_PIC_NEW_AETHERFOUNDATIONF               182
#define TRAINER_PIC_NEW_AGATHA_GEN1               183
#define TRAINER_PIC_NEW_AGATHA_GEN1RB               184
#define TRAINER_PIC_NEW_AGATHA_GEN3               185
#define TRAINER_PIC_NEW_AGATHA_LGPE               186
#define TRAINER_PIC_NEW_AKARI_ISEKAI               187
#define TRAINER_PIC_NEW_AKARI               188
#define TRAINER_PIC_NEW_ALAIN               189
#define TRAINER_PIC_NEW_ALDER               190
#define TRAINER_PIC_NEW_ALLISTER_MASTERS               191
#define TRAINER_PIC_NEW_ALLISTER               192
#define TRAINER_PIC_NEW_ANABEL_GEN3               193
#define TRAINER_PIC_NEW_ANABEL               194
#define TRAINER_PIC_NEW_ANTHE               195
#define TRAINER_PIC_NEW_ANTHEA               196
#define TRAINER_PIC_NEW_ANVIN               197
#define TRAINER_PIC_NEW_AQUAGRUNT               198
#define TRAINER_PIC_NEW_AQUAGRUNTF               199
#define TRAINER_PIC_NEW_ARCHER               200
#define TRAINER_PIC_NEW_ARCHIE_GEN3               201
#define TRAINER_PIC_NEW_ARCHIE_GEN6               202
#define TRAINER_PIC_NEW_AREZU               203
#define TRAINER_PIC_NEW_ARGENTA               204
#define TRAINER_PIC_NEW_ARIANA               205
#define TRAINER_PIC_NEW_AROMALADY_GEN3               206
#define TRAINER_PIC_NEW_AROMALADY_GEN3RS               207
#define TRAINER_PIC_NEW_AROMALADY_GEN6               208
#define TRAINER_PIC_NEW_AROMALADY               209
#define TRAINER_PIC_NEW_ARTIST_GEN4               210
#define TRAINER_PIC_NEW_ARTIST_GEN6               211
#define TRAINER_PIC_NEW_ARTIST_GEN8               212
#define TRAINER_PIC_NEW_ARTIST               213
#define TRAINER_PIC_NEW_ARTISTF_GEN6               214
#define TRAINER_PIC_NEW_ARVEN_S               215
#define TRAINER_PIC_NEW_ARVEN_V               216
#define TRAINER_PIC_NEW_ASH_ALOLA               217
#define TRAINER_PIC_NEW_ASH_CAPBACKWARD               218
#define TRAINER_PIC_NEW_ASH_HOENN               219
#define TRAINER_PIC_NEW_ASH_JOHTO               220
#define TRAINER_PIC_NEW_ASH_KALOS               221
#define TRAINER_PIC_NEW_ASH_SINNOH               222
#define TRAINER_PIC_NEW_ASH_UNOVA               223
#define TRAINER_PIC_NEW_ASH               224
#define TRAINER_PIC_NEW_AVERY               225
#define TRAINER_PIC_NEW_AZ               226
#define TRAINER_PIC_NEW_BACKERS               227
#define TRAINER_PIC_NEW_BACKERSF               228
#define TRAINER_PIC_NEW_BACKPACKER_GEN6               229
#define TRAINER_PIC_NEW_BACKPACKER_GEN8               230
#define TRAINER_PIC_NEW_BACKPACKER               231
#define TRAINER_PIC_NEW_BACKPACKERF               232
#define TRAINER_PIC_NEW_BAKER               233
#define TRAINER_PIC_NEW_BALLGUY               234
#define TRAINER_PIC_NEW_BARRY               235
#define TRAINER_PIC_NEW_BATTLEGIRL_GEN3               236
#define TRAINER_PIC_NEW_BATTLEGIRL_GEN4               237
#define TRAINER_PIC_NEW_BATTLEGIRL_GEN6               238
#define TRAINER_PIC_NEW_BATTLEGIRL_GEN6XY               239
#define TRAINER_PIC_NEW_BATTLEGIRL               240
#define TRAINER_PIC_NEW_BEA_MASTERS               241
#define TRAINER_PIC_NEW_BEA               242
#define TRAINER_PIC_NEW_BEAUTY_GEN1               243
#define TRAINER_PIC_NEW_BEAUTY_GEN1RB               244
#define TRAINER_PIC_NEW_BEAUTY_GEN2               245
#define TRAINER_PIC_NEW_BEAUTY_GEN2JP               246
#define TRAINER_PIC_NEW_BEAUTY_GEN3               247
#define TRAINER_PIC_NEW_BEAUTY_GEN3RS               248
#define TRAINER_PIC_NEW_BEAUTY_GEN4DP               249
#define TRAINER_PIC_NEW_BEAUTY_GEN5BW2               250
#define TRAINER_PIC_NEW_BEAUTY_GEN6               251
#define TRAINER_PIC_NEW_BEAUTY_GEN6XY               252
#define TRAINER_PIC_NEW_BEAUTY_GEN7               253
#define TRAINER_PIC_NEW_BEAUTY_GEN8               254
#define TRAINER_PIC_NEW_BEAUTY_MASTERS               255
#define TRAINER_PIC_NEW_BEAUTY               256
#define TRAINER_PIC_NEW_BEDE_LEADER               257
#define TRAINER_PIC_NEW_BEDE               258
#define TRAINER_PIC_NEW_BELLELBA               259
#define TRAINER_PIC_NEW_BELLEPA               260
#define TRAINER_PIC_NEW_BELLHOP               261
#define TRAINER_PIC_NEW_BELLIS               262
#define TRAINER_PIC_NEW_BENGA               263
#define TRAINER_PIC_NEW_BENI_NINJA               264
#define TRAINER_PIC_NEW_BENI               265
#define TRAINER_PIC_NEW_BERTHA               266
#define TRAINER_PIC_NEW_BIANCA_PWT               267
#define TRAINER_PIC_NEW_BIANCA               268
#define TRAINER_PIC_NEW_BIKER_GEN1               269
#define TRAINER_PIC_NEW_BIKER_GEN1RB               270
#define TRAINER_PIC_NEW_BIKER_GEN2               271
#define TRAINER_PIC_NEW_BIKER_GEN3               272
#define TRAINER_PIC_NEW_BIKER_GEN4               273
#define TRAINER_PIC_NEW_BIKER               274
#define TRAINER_PIC_NEW_BILL_GEN3               275
#define TRAINER_PIC_NEW_BIRCH_GEN3               276
#define TRAINER_PIC_NEW_BIRCH               277
#define TRAINER_PIC_NEW_BIRDKEEPER_GEN1               278
#define TRAINER_PIC_NEW_BIRDKEEPER_GEN1RB               279
#define TRAINER_PIC_NEW_BIRDKEEPER_GEN2               280
#define TRAINER_PIC_NEW_BIRDKEEPER_GEN3               281
#define TRAINER_PIC_NEW_BIRDKEEPER_GEN3RS               282
#define TRAINER_PIC_NEW_BIRDKEEPER_GEN4DP               283
#define TRAINER_PIC_NEW_BIRDKEEPER_GEN6               284
#define TRAINER_PIC_NEW_BIRDKEEPER               285
#define TRAINER_PIC_NEW_BLACKBELT_GEN1               286
#define TRAINER_PIC_NEW_BLACKBELT_GEN1RB               287
#define TRAINER_PIC_NEW_BLACKBELT_GEN2               288
#define TRAINER_PIC_NEW_BLACKBELT_GEN3               289
#define TRAINER_PIC_NEW_BLACKBELT_GEN3RS               290
#define TRAINER_PIC_NEW_BLACKBELT_GEN4               291
#define TRAINER_PIC_NEW_BLACKBELT_GEN4DP               292
#define TRAINER_PIC_NEW_BLACKBELT_GEN6               293
#define TRAINER_PIC_NEW_BLACKBELT_GEN7               294
#define TRAINER_PIC_NEW_BLACKBELT_GEN8               295
#define TRAINER_PIC_NEW_BLACKBELT               296
#define TRAINER_PIC_NEW_BLAINE_GEN1               297
#define TRAINER_PIC_NEW_BLAINE_GEN1RB               298
#define TRAINER_PIC_NEW_BLAINE_GEN2               299
#define TRAINER_PIC_NEW_BLAINE_GEN3               300
#define TRAINER_PIC_NEW_BLAINE_LGPE               301
#define TRAINER_PIC_NEW_BLAINE               302
#define TRAINER_PIC_NEW_BLUE_GEN1               303
#define TRAINER_PIC_NEW_BLUE_GEN1CHAMPION               304
#define TRAINER_PIC_NEW_BLUE_GEN1RB               305
#define TRAINER_PIC_NEW_BLUE_GEN1RBCHAMPION               306
#define TRAINER_PIC_NEW_BLUE_GEN1RBTWO               307
#define TRAINER_PIC_NEW_BLUE_GEN1TWO               308
#define TRAINER_PIC_NEW_BLUE_GEN2               309
#define TRAINER_PIC_NEW_BLUE_GEN3               310
#define TRAINER_PIC_NEW_BLUE_GEN3CHAMPION               311
#define TRAINER_PIC_NEW_BLUE_GEN3TWO               312
#define TRAINER_PIC_NEW_BLUE_GEN7               313
#define TRAINER_PIC_NEW_BLUE_LGPE               314
#define TRAINER_PIC_NEW_BLUE_MASTERS               315
#define TRAINER_PIC_NEW_BLUE               316
#define TRAINER_PIC_NEW_BOARDER_GEN2               317
#define TRAINER_PIC_NEW_BOARDER               318
#define TRAINER_PIC_NEW_BRANDON_GEN3               319
#define TRAINER_PIC_NEW_BRASSIUS               320
#define TRAINER_PIC_NEW_BRAWLY_GEN3               321
#define TRAINER_PIC_NEW_BRAWLY_GEN6               322
#define TRAINER_PIC_NEW_BRAWLY               323
#define TRAINER_PIC_NEW_BRENDAN_CONTEST               324
#define TRAINER_PIC_NEW_BRENDAN_GEN3               325
#define TRAINER_PIC_NEW_BRENDAN_GEN3RS               326
#define TRAINER_PIC_NEW_BRENDAN_MASTERS               327
#define TRAINER_PIC_NEW_BRENDAN               328
#define TRAINER_PIC_NEW_BRIGETTE               329
#define TRAINER_PIC_NEW_BROCK_GEN1               330
#define TRAINER_PIC_NEW_BROCK_GEN1RB               331
#define TRAINER_PIC_NEW_BROCK_GEN2               332
#define TRAINER_PIC_NEW_BROCK_GEN3               333
#define TRAINER_PIC_NEW_BROCK_LGPE               334
#define TRAINER_PIC_NEW_BROCK_MASTERS               335
#define TRAINER_PIC_NEW_BROCK               336
#define TRAINER_PIC_NEW_BRUNO_GEN1               337
#define TRAINER_PIC_NEW_BRUNO_GEN1RB               338
#define TRAINER_PIC_NEW_BRUNO_GEN2               339
#define TRAINER_PIC_NEW_BRUNO_GEN3               340
#define TRAINER_PIC_NEW_BRUNO               341
#define TRAINER_PIC_NEW_BRYCEN               342
#define TRAINER_PIC_NEW_BRYCENMAN               343
#define TRAINER_PIC_NEW_BRYONY               344
#define TRAINER_PIC_NEW_BUCK               345
#define TRAINER_PIC_NEW_BUGCATCHER_GEN1               346
#define TRAINER_PIC_NEW_BUGCATCHER_GEN1RB               347
#define TRAINER_PIC_NEW_BUGCATCHER_GEN2               348
#define TRAINER_PIC_NEW_BUGCATCHER_GEN3               349
#define TRAINER_PIC_NEW_BUGCATCHER_GEN3RS               350
#define TRAINER_PIC_NEW_BUGCATCHER_GEN4DP               351
#define TRAINER_PIC_NEW_BUGCATCHER_GEN6               352
#define TRAINER_PIC_NEW_BUGCATCHER               353
#define TRAINER_PIC_NEW_BUGMANIAC_GEN3               354
#define TRAINER_PIC_NEW_BUGMANIAC_GEN6               355
#define TRAINER_PIC_NEW_BUGSY_GEN2               356
#define TRAINER_PIC_NEW_BUGSY               357
#define TRAINER_PIC_NEW_BURGH_MASTERS               358
#define TRAINER_PIC_NEW_BURGH               359
#define TRAINER_PIC_NEW_BURGLAR_GEN1               360
#define TRAINER_PIC_NEW_BURGLAR_GEN1RB               361
#define TRAINER_PIC_NEW_BURGLAR_GEN2               362
#define TRAINER_PIC_NEW_BURGLAR_GEN3               363
#define TRAINER_PIC_NEW_BURGLAR_LGPE               364
#define TRAINER_PIC_NEW_BURGLAR               365
#define TRAINER_PIC_NEW_BURNET_RADAR               366
#define TRAINER_PIC_NEW_BURNET               367
#define TRAINER_PIC_NEW_BUTLER               368
#define TRAINER_PIC_NEW_BYRON               369
#define TRAINER_PIC_NEW_CABBIE               370
#define TRAINER_PIC_NEW_CAFEMASTER               371
#define TRAINER_PIC_NEW_CAITLIN_GEN4               372
#define TRAINER_PIC_NEW_CAITLIN_MASTERS               373
#define TRAINER_PIC_NEW_CAITLIN               374
#define TRAINER_PIC_NEW_CALABA               375
#define TRAINER_PIC_NEW_CALEM               376
#define TRAINER_PIC_NEW_CAMERAMAN_GEN6               377
#define TRAINER_PIC_NEW_CAMERAMAN_GEN8               378
#define TRAINER_PIC_NEW_CAMERAMAN               379
#define TRAINER_PIC_NEW_CAMPER_GEN2               380
#define TRAINER_PIC_NEW_CAMPER_GEN3               381
#define TRAINER_PIC_NEW_CAMPER_GEN3RS               382
#define TRAINER_PIC_NEW_CAMPER_GEN6               383
#define TRAINER_PIC_NEW_CAMPER               384
#define TRAINER_PIC_NEW_CANDICE               385
#define TRAINER_PIC_NEW_CARALISS               386
#define TRAINER_PIC_NEW_CEDRICJUNIPER               387
#define TRAINER_PIC_NEW_CELIO               388
#define TRAINER_PIC_NEW_CHANNELER_GEN1               389
#define TRAINER_PIC_NEW_CHANNELER_GEN1RB               390
#define TRAINER_PIC_NEW_CHANNELER_GEN3               391
#define TRAINER_PIC_NEW_CHANNELER_LGPE               392
#define TRAINER_PIC_NEW_CHARM               393
#define TRAINER_PIC_NEW_CHARON               394
#define TRAINER_PIC_NEW_CHASE               395
#define TRAINER_PIC_NEW_CHEF               396
#define TRAINER_PIC_NEW_CHEREN_GEN5BW2               397
#define TRAINER_PIC_NEW_CHEREN               398
#define TRAINER_PIC_NEW_CHERYL               399
#define TRAINER_PIC_NEW_CHILI               400
#define TRAINER_PIC_NEW_CHOY               401
#define TRAINER_PIC_NEW_CHUCK_GEN2               402
#define TRAINER_PIC_NEW_CHUCK               403
#define TRAINER_PIC_NEW_CILAN               404
#define TRAINER_PIC_NEW_CLAIR_GEN2               405
#define TRAINER_PIC_NEW_CLAIR               406
#define TRAINER_PIC_NEW_CLAVELL_S               407
#define TRAINER_PIC_NEW_CLAY               408
#define TRAINER_PIC_NEW_CLEMONT               409
#define TRAINER_PIC_NEW_CLERK_BOSS               410
#define TRAINER_PIC_NEW_CLERK_GEN8               411
#define TRAINER_PIC_NEW_CLERK               412
#define TRAINER_PIC_NEW_CLERKF_GEN8               413
#define TRAINER_PIC_NEW_CLERKF               414
#define TRAINER_PIC_NEW_CLOVER               415
#define TRAINER_PIC_NEW_CLOWN               416
#define TRAINER_PIC_NEW_COGITA               417
#define TRAINER_PIC_NEW_COIN               418
#define TRAINER_PIC_NEW_COLLECTOR_GEN3               419
#define TRAINER_PIC_NEW_COLLECTOR_GEN6               420
#define TRAINER_PIC_NEW_COLLECTOR_GEN7               421
#define TRAINER_PIC_NEW_COLLECTOR_MASTERS               422
#define TRAINER_PIC_NEW_COLLECTOR               423
#define TRAINER_PIC_NEW_COLRESS_GEN7               424
#define TRAINER_PIC_NEW_COLRESS               425
#define TRAINER_PIC_NEW_COLZA               426
#define TRAINER_PIC_NEW_CONCORDIA               427
#define TRAINER_PIC_NEW_COOK_GEN7               428
#define TRAINER_PIC_NEW_COOK               429
#define TRAINER_PIC_NEW_COURTNEY_GEN3               430
#define TRAINER_PIC_NEW_COURTNEY               431
#define TRAINER_PIC_NEW_COWGIRL               432
#define TRAINER_PIC_NEW_CRASHERWAKE               433
#define TRAINER_PIC_NEW_CRESS               434
#define TRAINER_PIC_NEW_CRUSHGIRL_GEN3               435
#define TRAINER_PIC_NEW_CRUSHKIN_GEN3               436
#define TRAINER_PIC_NEW_CUEBALL_GEN1               437
#define TRAINER_PIC_NEW_CUEBALL_GEN1RB               438
#define TRAINER_PIC_NEW_CUEBALL_GEN3               439
#define TRAINER_PIC_NEW_CYCLIST_GEN4               440
#define TRAINER_PIC_NEW_CYCLIST               441
#define TRAINER_PIC_NEW_CYCLISTF_GEN4               442
#define TRAINER_PIC_NEW_CYCLISTF               443
#define TRAINER_PIC_NEW_CYLLENE               444
#define TRAINER_PIC_NEW_CYNTHIA_ANIME               445
#define TRAINER_PIC_NEW_CYNTHIA_ANIME2               446
#define TRAINER_PIC_NEW_CYNTHIA_GEN4               447
#define TRAINER_PIC_NEW_CYNTHIA_GEN7               448
#define TRAINER_PIC_NEW_CYNTHIA_MASTERS               449
#define TRAINER_PIC_NEW_CYNTHIA_MASTERS2               450
#define TRAINER_PIC_NEW_CYNTHIA_MASTERS3               451
#define TRAINER_PIC_NEW_CYNTHIA               452
#define TRAINER_PIC_NEW_CYRUS_MASTERS               453
#define TRAINER_PIC_NEW_CYRUS               454
#define TRAINER_PIC_NEW_DAGERO               455
#define TRAINER_PIC_NEW_DAHLIA               456
#define TRAINER_PIC_NEW_DAISY_GEN3               457
#define TRAINER_PIC_NEW_DANCER_GEN7               458
#define TRAINER_PIC_NEW_DANCER_GEN8               459
#define TRAINER_PIC_NEW_DANCER               460
#define TRAINER_PIC_NEW_DARACH_CAITLIN               461
#define TRAINER_PIC_NEW_DARACH               462
#define TRAINER_PIC_NEW_DAWN_CONTEST               463
#define TRAINER_PIC_NEW_DAWN_GEN4PT               464
#define TRAINER_PIC_NEW_DAWN_MASTERS               465
#define TRAINER_PIC_NEW_DAWN_MASTERS2               466
#define TRAINER_PIC_NEW_DAWN               467
#define TRAINER_PIC_NEW_DELINQUENT               468
#define TRAINER_PIC_NEW_DEPOTAGENT               469
#define TRAINER_PIC_NEW_DEXIO_GEN6               470
#define TRAINER_PIC_NEW_DEXIO               471
#define TRAINER_PIC_NEW_DIANTHA_MASTERS               472
#define TRAINER_PIC_NEW_DIANTHA               473
#define TRAINER_PIC_NEW_DOCTOR_GEN8               474
#define TRAINER_PIC_NEW_DOCTOR               475
#define TRAINER_PIC_NEW_DOCTORF_GEN8               476
#define TRAINER_PIC_NEW_DOUBLETEAM               477
#define TRAINER_PIC_NEW_DRAGONTAMER_GEN3               478
#define TRAINER_PIC_NEW_DRAGONTAMER_GEN6               479
#define TRAINER_PIC_NEW_DRAGONTAMER               480
#define TRAINER_PIC_NEW_DRAKE_GEN3               481
#define TRAINER_PIC_NEW_DRASNA               482
#define TRAINER_PIC_NEW_DRAYDEN               483
#define TRAINER_PIC_NEW_DULSE               484
#define TRAINER_PIC_NEW_ELAINE               485
#define TRAINER_PIC_NEW_ELESA_GEN5BW2               486
#define TRAINER_PIC_NEW_ELESA_MASTERS               487
#define TRAINER_PIC_NEW_ELESA               488
#define TRAINER_PIC_NEW_ELIO_USUM               489
#define TRAINER_PIC_NEW_ELIO               490
#define TRAINER_PIC_NEW_ELM               491
#define TRAINER_PIC_NEW_EMMA               492
#define TRAINER_PIC_NEW_EMMET_MASTERS               493
#define TRAINER_PIC_NEW_EMMET               494
#define TRAINER_PIC_NEW_ENGINEER_GEN1               495
#define TRAINER_PIC_NEW_ENGINEER_GEN1RB               496
#define TRAINER_PIC_NEW_ENGINEER_GEN3               497
#define TRAINER_PIC_NEW_ERIKA_GEN1               498
#define TRAINER_PIC_NEW_ERIKA_GEN1RB               499
#define TRAINER_PIC_NEW_ERIKA_GEN2               500
#define TRAINER_PIC_NEW_ERIKA_GEN3               501
#define TRAINER_PIC_NEW_ERIKA_LGPE               502
#define TRAINER_PIC_NEW_ERIKA_MASTERS               503
#define TRAINER_PIC_NEW_ERIKA_MASTERS2               504
#define TRAINER_PIC_NEW_ERIKA               505
#define TRAINER_PIC_NEW_ESSENTIA               506
#define TRAINER_PIC_NEW_ETHAN_GEN2               507
#define TRAINER_PIC_NEW_ETHAN_GEN2ALT               508
#define TRAINER_PIC_NEW_ETHAN_GEN2C               509
#define TRAINER_PIC_NEW_ETHAN_MASTERS               510
#define TRAINER_PIC_NEW_ETHAN_POKEATHLON               511
#define TRAINER_PIC_NEW_ETHAN               512
#define TRAINER_PIC_NEW_EUSINE_GEN2               513
#define TRAINER_PIC_NEW_EUSINE               514
#define TRAINER_PIC_NEW_EVELYN               515
#define TRAINER_PIC_NEW_EXPERT_GEN3               516
#define TRAINER_PIC_NEW_EXPERT_GEN6               517
#define TRAINER_PIC_NEW_EXPERTF_GEN3               518
#define TRAINER_PIC_NEW_EXPERTF_GEN6               519
#define TRAINER_PIC_NEW_FABA               520
#define TRAINER_PIC_NEW_FAIRYTALEGIRL               521
#define TRAINER_PIC_NEW_FALKNER_GEN2               522
#define TRAINER_PIC_NEW_FALKNER               523
#define TRAINER_PIC_NEW_FANTINA               524
#define TRAINER_PIC_NEW_FENNEL               525
#define TRAINER_PIC_NEW_FIREBREATHER_GEN2               526
#define TRAINER_PIC_NEW_FIREBREATHER               527
#define TRAINER_PIC_NEW_FIREFIGHTER               528
#define TRAINER_PIC_NEW_FISHER_GEN8               529
#define TRAINER_PIC_NEW_FISHERMAN_GEN1               530
#define TRAINER_PIC_NEW_FISHERMAN_GEN1RB               531
#define TRAINER_PIC_NEW_FISHERMAN_GEN2JP               532
#define TRAINER_PIC_NEW_FISHERMAN_GEN3               533
#define TRAINER_PIC_NEW_FISHERMAN_GEN3RS               534
#define TRAINER_PIC_NEW_FISHERMAN_GEN4               535
#define TRAINER_PIC_NEW_FISHERMAN_GEN6               536
#define TRAINER_PIC_NEW_FISHERMAN_GEN6XY               537
#define TRAINER_PIC_NEW_FISHERMAN_GEN7               538
#define TRAINER_PIC_NEW_FISHERMAN               539
#define TRAINER_PIC_NEW_FLANNERY_GEN3               540
#define TRAINER_PIC_NEW_FLANNERY_GEN6               541
#define TRAINER_PIC_NEW_FLANNERY               542
#define TRAINER_PIC_NEW_FLINT               543
#define TRAINER_PIC_NEW_FLORIAN_S               544
#define TRAINER_PIC_NEW_FREEDIVER               545
#define TRAINER_PIC_NEW_FURISODEGIRL_BLACK               546
#define TRAINER_PIC_NEW_FURISODEGIRL_BLUE               547
#define TRAINER_PIC_NEW_FURISODEGIRL_PINK               548
#define TRAINER_PIC_NEW_FURISODEGIRL_WHITE               549
#define TRAINER_PIC_NEW_GAERIC               550
#define TRAINER_PIC_NEW_GALACTICGRUNT               551
#define TRAINER_PIC_NEW_GALACTICGRUNTF               552
#define TRAINER_PIC_NEW_GAMBLER_GEN1               553
#define TRAINER_PIC_NEW_GAMBLER_GEN1RB               554
#define TRAINER_PIC_NEW_GAMBLER               555
#define TRAINER_PIC_NEW_GAMER_GEN3               556
#define TRAINER_PIC_NEW_GARCON               557
#define TRAINER_PIC_NEW_GARDENER               558
#define TRAINER_PIC_NEW_GARDENIA               559
#define TRAINER_PIC_NEW_GEETA               560
#define TRAINER_PIC_NEW_GENTLEMAN_GEN1               561
#define TRAINER_PIC_NEW_GENTLEMAN_GEN1RB               562
#define TRAINER_PIC_NEW_GENTLEMAN_GEN2               563
#define TRAINER_PIC_NEW_GENTLEMAN_GEN3               564
#define TRAINER_PIC_NEW_GENTLEMAN_GEN3RS               565
#define TRAINER_PIC_NEW_GENTLEMAN_GEN4               566
#define TRAINER_PIC_NEW_GENTLEMAN_GEN4DP               567
#define TRAINER_PIC_NEW_GENTLEMAN_GEN6               568
#define TRAINER_PIC_NEW_GENTLEMAN_GEN6XY               569
#define TRAINER_PIC_NEW_GENTLEMAN_GEN7               570
#define TRAINER_PIC_NEW_GENTLEMAN_GEN8               571
#define TRAINER_PIC_NEW_GENTLEMAN_LGPE               572
#define TRAINER_PIC_NEW_GENTLEMAN               573
#define TRAINER_PIC_NEW_GHETSIS_GEN5BW               574
#define TRAINER_PIC_NEW_GHETSIS               575
#define TRAINER_PIC_NEW_GINTER               576
#define TRAINER_PIC_NEW_GIOVANNI_GEN1               577
#define TRAINER_PIC_NEW_GIOVANNI_GEN1RB               578
#define TRAINER_PIC_NEW_GIOVANNI_GEN3               579
#define TRAINER_PIC_NEW_GIOVANNI_LGPE               580
#define TRAINER_PIC_NEW_GIOVANNI_MASTERS               581
#define TRAINER_PIC_NEW_GIOVANNI               582
#define TRAINER_PIC_NEW_GLACIA_GEN3               583
#define TRAINER_PIC_NEW_GLACIA               584
#define TRAINER_PIC_NEW_GLADION_STANCE               585
#define TRAINER_PIC_NEW_GLADION               586
#define TRAINER_PIC_NEW_GLORIA_DOJO               587
#define TRAINER_PIC_NEW_GLORIA_MASTERS               588
#define TRAINER_PIC_NEW_GLORIA               589
#define TRAINER_PIC_NEW_GOLFER               590
#define TRAINER_PIC_NEW_GORDIE               591
#define TRAINER_PIC_NEW_GRACE               592
#define TRAINER_PIC_NEW_GRANT               593
#define TRAINER_PIC_NEW_GREEN               594
#define TRAINER_PIC_NEW_GRETA_GEN3               595
#define TRAINER_PIC_NEW_GRIMSLEY_GEN7               596
#define TRAINER_PIC_NEW_GRIMSLEY_MASTERS               597
#define TRAINER_PIC_NEW_GRIMSLEY               598
#define TRAINER_PIC_NEW_GRUSHA               599
#define TRAINER_PIC_NEW_GUITARIST_GEN2               600
#define TRAINER_PIC_NEW_GUITARIST_GEN3               601
#define TRAINER_PIC_NEW_GUITARIST_GEN4               602
#define TRAINER_PIC_NEW_GUITARIST_GEN6               603
#define TRAINER_PIC_NEW_GUITARIST               604
#define TRAINER_PIC_NEW_GUZMA_MASTERS               605
#define TRAINER_PIC_NEW_GUZMA               606
#define TRAINER_PIC_NEW_HALA               607
#define TRAINER_PIC_NEW_HAPU               608
#define TRAINER_PIC_NEW_HARLEQUIN               609
#define TRAINER_PIC_NEW_HASSEL               610
#define TRAINER_PIC_NEW_HAU_STANCE               611
#define TRAINER_PIC_NEW_HAU               612
#define TRAINER_PIC_NEW_HAYLEY               613
#define TRAINER_PIC_NEW_HEXMANIAC_GEN3               614
#define TRAINER_PIC_NEW_HEXMANIAC_GEN3JP               615
#define TRAINER_PIC_NEW_HEXMANIAC_GEN6               616
#define TRAINER_PIC_NEW_HIKER_GEN1               617
#define TRAINER_PIC_NEW_HIKER_GEN1RB               618
#define TRAINER_PIC_NEW_HIKER_GEN2               619
#define TRAINER_PIC_NEW_HIKER_GEN3               620
#define TRAINER_PIC_NEW_HIKER_GEN3RS               621
#define TRAINER_PIC_NEW_HIKER_GEN4               622
#define TRAINER_PIC_NEW_HIKER_GEN6               623
#define TRAINER_PIC_NEW_HIKER_GEN7               624
#define TRAINER_PIC_NEW_HIKER_GEN8               625
#define TRAINER_PIC_NEW_HIKER               626
#define TRAINER_PIC_NEW_HILBERT_DUELDISK               627
#define TRAINER_PIC_NEW_HILBERT_MASTERS               628
#define TRAINER_PIC_NEW_HILBERT_WONDERLAUNCHER               629
#define TRAINER_PIC_NEW_HILBERT               630
#define TRAINER_PIC_NEW_HILDA_DUELDISK               631
#define TRAINER_PIC_NEW_HILDA_MASTERS               632
#define TRAINER_PIC_NEW_HILDA_MASTERS2               633
#define TRAINER_PIC_NEW_HILDA_MASTERS3               634
#define TRAINER_PIC_NEW_HILDA_WONDERLAUNCHER               635
#define TRAINER_PIC_NEW_HILDA               636
#define TRAINER_PIC_NEW_HOOLIGANS               637
#define TRAINER_PIC_NEW_HOOPSTER               638
#define TRAINER_PIC_NEW_HOP               639
#define TRAINER_PIC_NEW_HUGH               640
#define TRAINER_PIC_NEW_IDOL               641
#define TRAINER_PIC_NEW_ILIMA               642
#define TRAINER_PIC_NEW_INFIELDER               643
#define TRAINER_PIC_NEW_INGO_HISUI               644
#define TRAINER_PIC_NEW_INGO_MASTERS               645
#define TRAINER_PIC_NEW_INGO               646
#define TRAINER_PIC_NEW_INTERVIEWERS_GEN3               647
#define TRAINER_PIC_NEW_INTERVIEWERS_GEN6               648
#define TRAINER_PIC_NEW_INTERVIEWERS               649
#define TRAINER_PIC_NEW_IONO               650
#define TRAINER_PIC_NEW_IRIDA               651
#define TRAINER_PIC_NEW_IRIS_GEN5BW2               652
#define TRAINER_PIC_NEW_IRIS_MASTERS               653
#define TRAINER_PIC_NEW_IRIS               654
#define TRAINER_PIC_NEW_ISCAN               655
#define TRAINER_PIC_NEW_JACQ               656
#define TRAINER_PIC_NEW_JANINE_GEN2               657
#define TRAINER_PIC_NEW_JANINE               658
#define TRAINER_PIC_NEW_JANITOR_GEN7               659
#define TRAINER_PIC_NEW_JANITOR               660
#define TRAINER_PIC_NEW_JASMINE_CONTEST               661
#define TRAINER_PIC_NEW_JASMINE_GEN2               662
#define TRAINER_PIC_NEW_JASMINE_MASTERS               663
#define TRAINER_PIC_NEW_JASMINE               664
#define TRAINER_PIC_NEW_JESSIEJAMES_GEN1               665
#define TRAINER_PIC_NEW_JOGGER               666
#define TRAINER_PIC_NEW_JOHANNA_CONTEST               667
#define TRAINER_PIC_NEW_JOHANNA               668
#define TRAINER_PIC_NEW_JRTRAINER_GEN1               669
#define TRAINER_PIC_NEW_JRTRAINER_GEN1RB               670
#define TRAINER_PIC_NEW_JRTRAINERF_GEN1               671
#define TRAINER_PIC_NEW_JRTRAINERF_GEN1RB               672
#define TRAINER_PIC_NEW_JUAN_GEN3               673
#define TRAINER_PIC_NEW_JUAN               674
#define TRAINER_PIC_NEW_JUGGLER_GEN1               675
#define TRAINER_PIC_NEW_JUGGLER_GEN1RB               676
#define TRAINER_PIC_NEW_JUGGLER_GEN2               677
#define TRAINER_PIC_NEW_JUGGLER_GEN3               678
#define TRAINER_PIC_NEW_JUGGLER               679
#define TRAINER_PIC_NEW_JULIANA_S               680
#define TRAINER_PIC_NEW_JUNIPER               681
#define TRAINER_PIC_NEW_JUPITER               682
#define TRAINER_PIC_NEW_KABU               683
#define TRAINER_PIC_NEW_KAHILI               684
#define TRAINER_PIC_NEW_KAMADO_ARMOR               685
#define TRAINER_PIC_NEW_KAMADO               686
#define TRAINER_PIC_NEW_KAREN_GEN2               687
#define TRAINER_PIC_NEW_KAREN               688
#define TRAINER_PIC_NEW_KATY               689
#define TRAINER_PIC_NEW_KIAWE               690
#define TRAINER_PIC_NEW_KIMONOGIRL_GEN2               691
#define TRAINER_PIC_NEW_KIMONOGIRL               692
#define TRAINER_PIC_NEW_KINDLER_GEN3               693
#define TRAINER_PIC_NEW_KINDLER_GEN6               694
#define TRAINER_PIC_NEW_KLARA               695
#define TRAINER_PIC_NEW_KOFU               696
#define TRAINER_PIC_NEW_KOGA_GEN1               697
#define TRAINER_PIC_NEW_KOGA_GEN1RB               698
#define TRAINER_PIC_NEW_KOGA_GEN2               699
#define TRAINER_PIC_NEW_KOGA_GEN3               700
#define TRAINER_PIC_NEW_KOGA_LGPE               701
#define TRAINER_PIC_NEW_KOGA               702
#define TRAINER_PIC_NEW_KORRINA_MASTERS               703
#define TRAINER_PIC_NEW_KORRINA               704
#define TRAINER_PIC_NEW_KRIS_GEN2               705
#define TRAINER_PIC_NEW_KRIS_MASTERS               706
#define TRAINER_PIC_NEW_KUKUI_STAND               707
#define TRAINER_PIC_NEW_KUKUI               708
#define TRAINER_PIC_NEW_KURT               709
#define TRAINER_PIC_NEW_LADY_GEN3               710
#define TRAINER_PIC_NEW_LADY_GEN3RS               711
#define TRAINER_PIC_NEW_LADY_GEN4               712
#define TRAINER_PIC_NEW_LADY_GEN6               713
#define TRAINER_PIC_NEW_LADY_GEN6ORAS               714
#define TRAINER_PIC_NEW_LADY               715
#define TRAINER_PIC_NEW_LANA               716
#define TRAINER_PIC_NEW_LANCE_GEN1               717
#define TRAINER_PIC_NEW_LANCE_GEN1RB               718
#define TRAINER_PIC_NEW_LANCE_GEN2               719
#define TRAINER_PIC_NEW_LANCE_GEN3               720
#define TRAINER_PIC_NEW_LANCE_LGPE               721
#define TRAINER_PIC_NEW_LANCE_MASTERS               722
#define TRAINER_PIC_NEW_LANCE               723
#define TRAINER_PIC_NEW_LANETTE               724
#define TRAINER_PIC_NEW_LARRY               725
#define TRAINER_PIC_NEW_LASS_GEN1               726
#define TRAINER_PIC_NEW_LASS_GEN1RB               727
#define TRAINER_PIC_NEW_LASS_GEN2               728
#define TRAINER_PIC_NEW_LASS_GEN3               729
#define TRAINER_PIC_NEW_LASS_GEN3RS               730
#define TRAINER_PIC_NEW_LASS_GEN4               731
#define TRAINER_PIC_NEW_LASS_GEN4DP               732
#define TRAINER_PIC_NEW_LASS_GEN6               733
#define TRAINER_PIC_NEW_LASS_GEN6ORAS               734
#define TRAINER_PIC_NEW_LASS_GEN7               735
#define TRAINER_PIC_NEW_LASS_GEN8               736
#define TRAINER_PIC_NEW_LASS               737
#define TRAINER_PIC_NEW_LAVENTON               738
#define TRAINER_PIC_NEW_LEAF_GEN3               739
#define TRAINER_PIC_NEW_LEAF_MASTERS               740
#define TRAINER_PIC_NEW_LEAGUESTAFF               741
#define TRAINER_PIC_NEW_LEAGUESTAFFF               742
#define TRAINER_PIC_NEW_LENORA               743
#define TRAINER_PIC_NEW_LEON_MASTERS               744
#define TRAINER_PIC_NEW_LEON_MASTERS2               745
#define TRAINER_PIC_NEW_LEON_TOWER               746
#define TRAINER_PIC_NEW_LEON               747
#define TRAINER_PIC_NEW_LI               748
#define TRAINER_PIC_NEW_LIAN               749
#define TRAINER_PIC_NEW_LILLIE_MASTERS               750
#define TRAINER_PIC_NEW_LILLIE_MASTERS2               751
#define TRAINER_PIC_NEW_LILLIE_MASTERS3               752
#define TRAINER_PIC_NEW_LILLIE_Z               753
#define TRAINER_PIC_NEW_LILLIE               754
#define TRAINER_PIC_NEW_LINEBACKER               755
#define TRAINER_PIC_NEW_LISIA               756
#define TRAINER_PIC_NEW_LIZA               757
#define TRAINER_PIC_NEW_LORELEI_GEN1               758
#define TRAINER_PIC_NEW_LORELEI_GEN1RB               759
#define TRAINER_PIC_NEW_LORELEI_GEN3               760
#define TRAINER_PIC_NEW_LORELEI_LGPE               761
#define TRAINER_PIC_NEW_LTSURGE_GEN1               762
#define TRAINER_PIC_NEW_LTSURGE_GEN1RB               763
#define TRAINER_PIC_NEW_LTSURGE_GEN2               764
#define TRAINER_PIC_NEW_LTSURGE_GEN3               765
#define TRAINER_PIC_NEW_LTSURGE               766
#define TRAINER_PIC_NEW_LUCAS_CONTEST               767
#define TRAINER_PIC_NEW_LUCAS_GEN4PT               768
#define TRAINER_PIC_NEW_LUCAS               769
#define TRAINER_PIC_NEW_LUCIAN               770
#define TRAINER_PIC_NEW_LUCY_GEN3               771
#define TRAINER_PIC_NEW_LUCY               772
#define TRAINER_PIC_NEW_LUSAMINE_MASTERS               773
#define TRAINER_PIC_NEW_LUSAMINE_NIHILEGO               774
#define TRAINER_PIC_NEW_LUSAMINE               775
#define TRAINER_PIC_NEW_LYRA_MASTERS               776
#define TRAINER_PIC_NEW_LYRA_MASTERS2               777
#define TRAINER_PIC_NEW_LYRA_POKEATHLON               778
#define TRAINER_PIC_NEW_LYRA               779
#define TRAINER_PIC_NEW_LYSANDRE               780
#define TRAINER_PIC_NEW_MADAME_GEN4               781
#define TRAINER_PIC_NEW_MADAME_GEN4DP               782
#define TRAINER_PIC_NEW_MADAME_GEN6               783
#define TRAINER_PIC_NEW_MADAME_GEN7               784
#define TRAINER_PIC_NEW_MADAME_GEN8               785
#define TRAINER_PIC_NEW_MADAME               786
#define TRAINER_PIC_NEW_MAGMAGRUNT               787
#define TRAINER_PIC_NEW_MAGMAGRUNTF               788
#define TRAINER_PIC_NEW_MAGNOLIA               789
#define TRAINER_PIC_NEW_MAI               790
#define TRAINER_PIC_NEW_MAID_GEN4               791
#define TRAINER_PIC_NEW_MAID_GEN6               792
#define TRAINER_PIC_NEW_MAID               793
#define TRAINER_PIC_NEW_MALLOW               794
#define TRAINER_PIC_NEW_MALVA               795
#define TRAINER_PIC_NEW_MARLEY               796
#define TRAINER_PIC_NEW_MARLON               797
#define TRAINER_PIC_NEW_MARNIE_LEAGUE               798
#define TRAINER_PIC_NEW_MARNIE_MASTERS               799
#define TRAINER_PIC_NEW_MARNIE_MASTERS2               800
#define TRAINER_PIC_NEW_MARNIE               801
#define TRAINER_PIC_NEW_MARS               802
#define TRAINER_PIC_NEW_MARSHAL               803
#define TRAINER_PIC_NEW_MATT_GEN3               804
#define TRAINER_PIC_NEW_MAXIE_GEN3               805
#define TRAINER_PIC_NEW_MAXIE_GEN6               806
#define TRAINER_PIC_NEW_MAY_CONTEST               807
#define TRAINER_PIC_NEW_MAY_GEN3               808
#define TRAINER_PIC_NEW_MAY_GEN3RS               809
#define TRAINER_PIC_NEW_MAY_MASTERS               810
#define TRAINER_PIC_NEW_MAY_MASTERS2               811
#define TRAINER_PIC_NEW_MAY_MASTERS3               812
#define TRAINER_PIC_NEW_MAY               813
#define TRAINER_PIC_NEW_MAYLENE               814
#define TRAINER_PIC_NEW_MEDIUM_GEN2JP               815
#define TRAINER_PIC_NEW_MEDIUM               816
#define TRAINER_PIC_NEW_MELA               817
#define TRAINER_PIC_NEW_MELLI               818
#define TRAINER_PIC_NEW_MELONY               819
#define TRAINER_PIC_NEW_MILO               820
#define TRAINER_PIC_NEW_MINA_LGPE               821
#define TRAINER_PIC_NEW_MINA               822
#define TRAINER_PIC_NEW_MIRA               823
#define TRAINER_PIC_NEW_MIRIAM               824
#define TRAINER_PIC_NEW_MISTY_GEN1               825
#define TRAINER_PIC_NEW_MISTY_GEN1RB               826
#define TRAINER_PIC_NEW_MISTY_GEN2               827
#define TRAINER_PIC_NEW_MISTY_GEN3               828
#define TRAINER_PIC_NEW_MISTY_LGPE               829
#define TRAINER_PIC_NEW_MISTY_MASTERS               830
#define TRAINER_PIC_NEW_MISTY               831
#define TRAINER_PIC_NEW_MODEL_GEN8               832
#define TRAINER_PIC_NEW_MOLAYNE               833
#define TRAINER_PIC_NEW_MOM_ALOLA               834
#define TRAINER_PIC_NEW_MOM_HOENN               835
#define TRAINER_PIC_NEW_MOM_JOHTO               836
#define TRAINER_PIC_NEW_MOM_UNOVA2               837
#define TRAINER_PIC_NEW_MORGAN               838
#define TRAINER_PIC_NEW_MORTY_GEN2               839
#define TRAINER_PIC_NEW_MORTY_MASTERS               840
#define TRAINER_PIC_NEW_MORTY_MASTERS2               841
#define TRAINER_PIC_NEW_MORTY               842
#define TRAINER_PIC_NEW_MRFUJI_GEN3               843
#define TRAINER_PIC_NEW_MUSICIAN_GEN8               844
#define TRAINER_PIC_NEW_MUSICIAN               845
#define TRAINER_PIC_NEW_MUSTARD_MASTER               846
#define TRAINER_PIC_NEW_MUSTARD               847
#define TRAINER_PIC_NEW_N_MASTERS               848
#define TRAINER_PIC_NEW_N_MASTERS2               849
#define TRAINER_PIC_NEW_N               850
#define TRAINER_PIC_NEW_NANU               851
#define TRAINER_PIC_NEW_NATE_DUELDISK               852
#define TRAINER_PIC_NEW_NATE_WONDERLAUNCHER               853
#define TRAINER_PIC_NEW_NATE               854
#define TRAINER_PIC_NEW_NEMONA_V               855
#define TRAINER_PIC_NEW_NESSA_MASTERS               856
#define TRAINER_PIC_NEW_NESSA               857
#define TRAINER_PIC_NEW_NINJABOY_GEN3               858
#define TRAINER_PIC_NEW_NINJABOY_GEN6               859
#define TRAINER_PIC_NEW_NINJABOY               860
#define TRAINER_PIC_NEW_NITA               861
#define TRAINER_PIC_NEW_NOLAND_GEN3               862
#define TRAINER_PIC_NEW_NOLAND               863
#define TRAINER_PIC_NEW_NORMAN_GEN3               864
#define TRAINER_PIC_NEW_NORMAN_GEN6               865
#define TRAINER_PIC_NEW_NORMAN               866
#define TRAINER_PIC_NEW_NURSE               867
#define TRAINER_PIC_NEW_NURSERYAIDE               868
#define TRAINER_PIC_NEW_OAK_GEN1               869
#define TRAINER_PIC_NEW_OAK_GEN1RB               870
#define TRAINER_PIC_NEW_OAK_GEN2               871
#define TRAINER_PIC_NEW_OAK_GEN3               872
#define TRAINER_PIC_NEW_OAK               873
#define TRAINER_PIC_NEW_OFFICER_GEN2               874
#define TRAINER_PIC_NEW_OFFICEWORKER               875
#define TRAINER_PIC_NEW_OFFICEWORKERF               876
#define TRAINER_PIC_NEW_OLDCOUPLE_GEN3               877
#define TRAINER_PIC_NEW_OLEANA               878
#define TRAINER_PIC_NEW_OLIVIA               879
#define TRAINER_PIC_NEW_OLYMPIA               880
#define TRAINER_PIC_NEW_OPAL               881
#define TRAINER_PIC_NEW_OWNER               882
#define TRAINER_PIC_NEW_PAINTER_GEN3               883
#define TRAINER_PIC_NEW_PALINA               884
#define TRAINER_PIC_NEW_PALMER               885
#define TRAINER_PIC_NEW_PARASOLLADY_GEN3               886
#define TRAINER_PIC_NEW_PARASOLLADY_GEN4               887
#define TRAINER_PIC_NEW_PARASOLLADY_GEN6               888
#define TRAINER_PIC_NEW_PARASOLLADY               889
#define TRAINER_PIC_NEW_PENNY               890
#define TRAINER_PIC_NEW_PEONIA               891
#define TRAINER_PIC_NEW_PEONY               892
#define TRAINER_PIC_NEW_PESSELLE               893
#define TRAINER_PIC_NEW_PETREL               894
#define TRAINER_PIC_NEW_PHOEBE_GEN3               895
#define TRAINER_PIC_NEW_PHOEBE_GEN6               896
#define TRAINER_PIC_NEW_PHYCO               897
#define TRAINER_PIC_NEW_PICNICKER_GEN2               898
#define TRAINER_PIC_NEW_PICNICKER_GEN3               899
#define TRAINER_PIC_NEW_PICNICKER_GEN3RS               900
#define TRAINER_PIC_NEW_PICNICKER_GEN6               901
#define TRAINER_PIC_NEW_PICNICKER               902
#define TRAINER_PIC_NEW_PIERS_LEAGUE               903
#define TRAINER_PIC_NEW_PIERS               904
#define TRAINER_PIC_NEW_PILOT               905
#define TRAINER_PIC_NEW_PLASMAGRUNT_GEN5BW               906
#define TRAINER_PIC_NEW_PLASMAGRUNT               907
#define TRAINER_PIC_NEW_PLASMAGRUNTF_GEN5BW               908
#define TRAINER_PIC_NEW_PLASMAGRUNTF               909
#define TRAINER_PIC_NEW_PLUMERIA_LEAGUE               910
#define TRAINER_PIC_NEW_PLUMERIA               911
#define TRAINER_PIC_NEW_POKEFAN_GEN2               912
#define TRAINER_PIC_NEW_POKEFAN_GEN3               913
#define TRAINER_PIC_NEW_POKEFAN_GEN4               914
#define TRAINER_PIC_NEW_POKEFAN_GEN6               915
#define TRAINER_PIC_NEW_POKEFAN_GEN6XY               916
#define TRAINER_PIC_NEW_POKEFAN               917
#define TRAINER_PIC_NEW_POKEFANF_GEN2               918
#define TRAINER_PIC_NEW_POKEFANF_GEN3               919
#define TRAINER_PIC_NEW_POKEFANF_GEN4               920
#define TRAINER_PIC_NEW_POKEFANF_GEN6               921
#define TRAINER_PIC_NEW_POKEFANF_GEN6XY               922
#define TRAINER_PIC_NEW_POKEFANF               923
#define TRAINER_PIC_NEW_POKEKID_GEN8               924
#define TRAINER_PIC_NEW_POKEKID               925
#define TRAINER_PIC_NEW_POKEKIDF_GEN8               926
#define TRAINER_PIC_NEW_POKEMANIAC_GEN1               927
#define TRAINER_PIC_NEW_POKEMANIAC_GEN1RB               928
#define TRAINER_PIC_NEW_POKEMANIAC_GEN2               929
#define TRAINER_PIC_NEW_POKEMANIAC_GEN3               930
#define TRAINER_PIC_NEW_POKEMANIAC_GEN3RS               931
#define TRAINER_PIC_NEW_POKEMANIAC_GEN6               932
#define TRAINER_PIC_NEW_POKEMANIAC               933
#define TRAINER_PIC_NEW_POKEMONBREEDER_GEN3               934
#define TRAINER_PIC_NEW_POKEMONBREEDER_GEN4               935
#define TRAINER_PIC_NEW_POKEMONBREEDER_GEN6               936
#define TRAINER_PIC_NEW_POKEMONBREEDER_GEN6XY               937
#define TRAINER_PIC_NEW_POKEMONBREEDER_GEN7               938
#define TRAINER_PIC_NEW_POKEMONBREEDER_GEN8               939
#define TRAINER_PIC_NEW_POKEMONBREEDER               940
#define TRAINER_PIC_NEW_POKEMONBREEDERF_GEN3               941
#define TRAINER_PIC_NEW_POKEMONBREEDERF_GEN3FRLG               942
#define TRAINER_PIC_NEW_POKEMONBREEDERF_GEN4               943
#define TRAINER_PIC_NEW_POKEMONBREEDERF_GEN6               944
#define TRAINER_PIC_NEW_POKEMONBREEDERF_GEN6XY               945
#define TRAINER_PIC_NEW_POKEMONBREEDERF_GEN7               946
#define TRAINER_PIC_NEW_POKEMONBREEDERF_GEN8               947
#define TRAINER_PIC_NEW_POKEMONBREEDERF               948
#define TRAINER_PIC_NEW_POKEMONCENTERLADY               949
#define TRAINER_PIC_NEW_POKEMONRANGER_GEN3               950
#define TRAINER_PIC_NEW_POKEMONRANGER_GEN3RS               951
#define TRAINER_PIC_NEW_POKEMONRANGER_GEN4               952
#define TRAINER_PIC_NEW_POKEMONRANGER_GEN6               953
#define TRAINER_PIC_NEW_POKEMONRANGER_GEN6XY               954
#define TRAINER_PIC_NEW_POKEMONRANGER               955
#define TRAINER_PIC_NEW_POKEMONRANGERF_GEN3               956
#define TRAINER_PIC_NEW_POKEMONRANGERF_GEN3RS               957
#define TRAINER_PIC_NEW_POKEMONRANGERF_GEN4               958
#define TRAINER_PIC_NEW_POKEMONRANGERF_GEN6               959
#define TRAINER_PIC_NEW_POKEMONRANGERF_GEN6XY               960
#define TRAINER_PIC_NEW_POKEMONRANGERF               961
#define TRAINER_PIC_NEW_POLICEMAN_GEN4               962
#define TRAINER_PIC_NEW_POLICEMAN_GEN7               963
#define TRAINER_PIC_NEW_POLICEMAN_GEN8               964
#define TRAINER_PIC_NEW_POLICEMAN               965
#define TRAINER_PIC_NEW_POPPY               966
#define TRAINER_PIC_NEW_POSTMAN               967
#define TRAINER_PIC_NEW_PRESCHOOLER_GEN6               968
#define TRAINER_PIC_NEW_PRESCHOOLER_GEN7               969
#define TRAINER_PIC_NEW_PRESCHOOLER               970
#define TRAINER_PIC_NEW_PRESCHOOLERF_GEN6               971
#define TRAINER_PIC_NEW_PRESCHOOLERF_GEN7               972
#define TRAINER_PIC_NEW_PRESCHOOLERF               973
#define TRAINER_PIC_NEW_PRESCHOOLERS               974
#define TRAINER_PIC_NEW_PROTON               975
#define TRAINER_PIC_NEW_PRYCE_GEN2               976
#define TRAINER_PIC_NEW_PRYCE               977
#define TRAINER_PIC_NEW_PSYCHIC_GEN1               978
#define TRAINER_PIC_NEW_PSYCHIC_GEN1RB               979
#define TRAINER_PIC_NEW_PSYCHIC_GEN2               980
#define TRAINER_PIC_NEW_PSYCHIC_GEN3               981
#define TRAINER_PIC_NEW_PSYCHIC_GEN3RS               982
#define TRAINER_PIC_NEW_PSYCHIC_GEN4               983
#define TRAINER_PIC_NEW_PSYCHIC_GEN6               984
#define TRAINER_PIC_NEW_PSYCHIC_LGPE               985
#define TRAINER_PIC_NEW_PSYCHIC               986
#define TRAINER_PIC_NEW_PSYCHICF_GEN3               987
#define TRAINER_PIC_NEW_PSYCHICF_GEN3RS               988
#define TRAINER_PIC_NEW_PSYCHICF_GEN4               989
#define TRAINER_PIC_NEW_PSYCHICF               990
#define TRAINER_PIC_NEW_PSYCHICFJP_GEN3               991
#define TRAINER_PIC_NEW_PUNKGIRL_GEN7               992
#define TRAINER_PIC_NEW_PUNKGIRL_MASTERS               993
#define TRAINER_PIC_NEW_PUNKGIRL               994
#define TRAINER_PIC_NEW_PUNKGUY_GEN7               995
#define TRAINER_PIC_NEW_PUNKGUY               996
#define TRAINER_PIC_NEW_RAIHAN_MASTERS               997
#define TRAINER_PIC_NEW_RAIHAN               998
#define TRAINER_PIC_NEW_RAILSTAFF               999
#define TRAINER_PIC_NEW_RAMOS               1000
#define TRAINER_PIC_NEW_RANCHER               1001
#define TRAINER_PIC_NEW_RED_GEN1               1002
#define TRAINER_PIC_NEW_RED_GEN1MAIN               1003
#define TRAINER_PIC_NEW_RED_GEN1RB               1004
#define TRAINER_PIC_NEW_RED_GEN1TITLE               1005
#define TRAINER_PIC_NEW_RED_GEN2               1006
#define TRAINER_PIC_NEW_RED_GEN3               1007
#define TRAINER_PIC_NEW_RED_GEN7               1008
#define TRAINER_PIC_NEW_RED_MASTERS               1009
#define TRAINER_PIC_NEW_RED_MASTERS2               1010
#define TRAINER_PIC_NEW_RED               1011
#define TRAINER_PIC_NEW_REI_ISEKAI               1012
#define TRAINER_PIC_NEW_REI               1013
#define TRAINER_PIC_NEW_REPORTER_GEN6               1014
#define TRAINER_PIC_NEW_REPORTER_GEN8               1015
#define TRAINER_PIC_NEW_REPORTER               1016
#define TRAINER_PIC_NEW_RICHBOY_GEN3               1017
#define TRAINER_PIC_NEW_RICHBOY_GEN4               1018
#define TRAINER_PIC_NEW_RICHBOY_GEN6               1019
#define TRAINER_PIC_NEW_RICHBOY_GEN6XY               1020
#define TRAINER_PIC_NEW_RICHBOY               1021
#define TRAINER_PIC_NEW_RIKA               1022
#define TRAINER_PIC_NEW_RILEY               1023
#define TRAINER_PIC_NEW_RISINGSTAR_GEN6               1024
#define TRAINER_PIC_NEW_RISINGSTAR               1025
#define TRAINER_PIC_NEW_RISINGSTARF_GEN6               1026
#define TRAINER_PIC_NEW_RISINGSTARF               1027
#define TRAINER_PIC_NEW_ROARK               1028
#define TRAINER_PIC_NEW_ROCKER_GEN1               1029
#define TRAINER_PIC_NEW_ROCKER_GEN1RB               1030
#define TRAINER_PIC_NEW_ROCKER_GEN3               1031
#define TRAINER_PIC_NEW_ROCKET_GEN1               1032
#define TRAINER_PIC_NEW_ROCKET_GEN1RB               1033
#define TRAINER_PIC_NEW_ROCKETEXECUTIVE_GEN2               1034
#define TRAINER_PIC_NEW_ROCKETEXECUTIVEF_GEN2               1035
#define TRAINER_PIC_NEW_ROCKETGRUNT_GEN2               1036
#define TRAINER_PIC_NEW_ROCKETGRUNT               1037
#define TRAINER_PIC_NEW_ROCKETGRUNTF_GEN2               1038
#define TRAINER_PIC_NEW_ROCKETGRUNTF               1039
#define TRAINER_PIC_NEW_ROLLERSKATER               1040
#define TRAINER_PIC_NEW_ROLLERSKATERF               1041
#define TRAINER_PIC_NEW_ROOD               1042
#define TRAINER_PIC_NEW_ROSA_DUELDISK               1043
#define TRAINER_PIC_NEW_ROSA_MASTERS               1044
#define TRAINER_PIC_NEW_ROSA_MASTERS2               1045
#define TRAINER_PIC_NEW_ROSA_POKESTAR               1046
#define TRAINER_PIC_NEW_ROSA_WONDERLAUNCHER               1047
#define TRAINER_PIC_NEW_ROSA               1048
#define TRAINER_PIC_NEW_ROSE_ZEROSUIT               1049
#define TRAINER_PIC_NEW_ROSE               1050
#define TRAINER_PIC_NEW_ROUGHNECK_GEN4               1051
#define TRAINER_PIC_NEW_ROUGHNECK               1052
#define TRAINER_PIC_NEW_ROWAN               1053
#define TRAINER_PIC_NEW_ROXANNE_GEN3               1054
#define TRAINER_PIC_NEW_ROXANNE_GEN6               1055
#define TRAINER_PIC_NEW_ROXANNE               1056
#define TRAINER_PIC_NEW_ROXIE               1057
#define TRAINER_PIC_NEW_RUINMANIAC_GEN3               1058
#define TRAINER_PIC_NEW_RUINMANIAC_GEN3RS               1059
#define TRAINER_PIC_NEW_RUINMANIAC_GEN6               1060
#define TRAINER_PIC_NEW_RUINMANIAC               1061
#define TRAINER_PIC_NEW_RYE               1062
#define TRAINER_PIC_NEW_RYME               1063
#define TRAINER_PIC_NEW_RYUKI               1064
#define TRAINER_PIC_NEW_SABI               1065
#define TRAINER_PIC_NEW_SABRINA_GEN1               1066
#define TRAINER_PIC_NEW_SABRINA_GEN1RB               1067
#define TRAINER_PIC_NEW_SABRINA_GEN2               1068
#define TRAINER_PIC_NEW_SABRINA_GEN3               1069
#define TRAINER_PIC_NEW_SABRINA_LGPE               1070
#define TRAINER_PIC_NEW_SABRINA_MASTERS               1071
#define TRAINER_PIC_NEW_SABRINA               1072
#define TRAINER_PIC_NEW_SADA               1073
#define TRAINER_PIC_NEW_SAGE_GEN2               1074
#define TRAINER_PIC_NEW_SAGE_GEN2JP               1075
#define TRAINER_PIC_NEW_SAGE               1076
#define TRAINER_PIC_NEW_SAILOR_GEN1               1077
#define TRAINER_PIC_NEW_SAILOR_GEN1RB               1078
#define TRAINER_PIC_NEW_SAILOR_GEN2               1079
#define TRAINER_PIC_NEW_SAILOR_GEN3               1080
#define TRAINER_PIC_NEW_SAILOR_GEN3JP               1081
#define TRAINER_PIC_NEW_SAILOR_GEN3RS               1082
#define TRAINER_PIC_NEW_SAILOR_GEN6               1083
#define TRAINER_PIC_NEW_SAILOR               1084
#define TRAINER_PIC_NEW_SAMSONOAK               1085
#define TRAINER_PIC_NEW_SANQUA               1086
#define TRAINER_PIC_NEW_SATURN               1087
#define TRAINER_PIC_NEW_SCHOOLBOY_GEN2               1088
#define TRAINER_PIC_NEW_SCHOOLBOY               1089
#define TRAINER_PIC_NEW_SCHOOLGIRL               1090
#define TRAINER_PIC_NEW_SCHOOLKID_GEN3               1091
#define TRAINER_PIC_NEW_SCHOOLKID_GEN4               1092
#define TRAINER_PIC_NEW_SCHOOLKID_GEN4DP               1093
#define TRAINER_PIC_NEW_SCHOOLKID_GEN6               1094
#define TRAINER_PIC_NEW_SCHOOLKID_GEN8               1095
#define TRAINER_PIC_NEW_SCHOOLKID               1096
#define TRAINER_PIC_NEW_SCHOOLKIDF_GEN3               1097
#define TRAINER_PIC_NEW_SCHOOLKIDF_GEN4               1098
#define TRAINER_PIC_NEW_SCHOOLKIDF_GEN6               1099
#define TRAINER_PIC_NEW_SCHOOLKIDF_GEN8               1100
#define TRAINER_PIC_NEW_SCHOOLKIDF               1101
#define TRAINER_PIC_NEW_SCIENTIST_GEN1               1102
#define TRAINER_PIC_NEW_SCIENTIST_GEN1RB               1103
#define TRAINER_PIC_NEW_SCIENTIST_GEN2               1104
#define TRAINER_PIC_NEW_SCIENTIST_GEN3               1105
#define TRAINER_PIC_NEW_SCIENTIST_GEN4               1106
#define TRAINER_PIC_NEW_SCIENTIST_GEN4DP               1107
#define TRAINER_PIC_NEW_SCIENTIST_GEN6               1108
#define TRAINER_PIC_NEW_SCIENTIST_GEN7               1109
#define TRAINER_PIC_NEW_SCIENTIST               1110
#define TRAINER_PIC_NEW_SCIENTISTF_GEN6               1111
#define TRAINER_PIC_NEW_SCIENTISTF               1112
#define TRAINER_PIC_NEW_SCOTT               1113
#define TRAINER_PIC_NEW_SCUBADIVER               1114
#define TRAINER_PIC_NEW_SECURITYCORPS               1115
#define TRAINER_PIC_NEW_SECURITYCORPSF               1116
#define TRAINER_PIC_NEW_SELENE_USUM               1117
#define TRAINER_PIC_NEW_SELENE               1118
#define TRAINER_PIC_NEW_SERENA_MASTERS               1119
#define TRAINER_PIC_NEW_SERENA_MASTERS2               1120
#define TRAINER_PIC_NEW_SERENA               1121
#define TRAINER_PIC_NEW_SHADOWTRIAD               1122
#define TRAINER_PIC_NEW_SHAUNA               1123
#define TRAINER_PIC_NEW_SHAUNTAL               1124
#define TRAINER_PIC_NEW_SHELLY_GEN3               1125
#define TRAINER_PIC_NEW_SHELLY               1126
#define TRAINER_PIC_NEW_SHIELBERT               1127
#define TRAINER_PIC_NEW_SIDNEY_GEN3               1128
#define TRAINER_PIC_NEW_SIDNEY               1129
#define TRAINER_PIC_NEW_SIEBOLD_MASTERS               1130
#define TRAINER_PIC_NEW_SIEBOLD               1131
#define TRAINER_PIC_NEW_SIGHTSEER               1132
#define TRAINER_PIC_NEW_SIGHTSEERF               1133
#define TRAINER_PIC_NEW_SILVER_GEN2               1134
#define TRAINER_PIC_NEW_SILVER_GEN2KANTO               1135
#define TRAINER_PIC_NEW_SILVER               1136
#define TRAINER_PIC_NEW_SINA_GEN6               1137
#define TRAINER_PIC_NEW_SINA               1138
#define TRAINER_PIC_NEW_SISANDBRO_GEN3               1139
#define TRAINER_PIC_NEW_SISANDBRO_GEN3RS               1140
#define TRAINER_PIC_NEW_SISANDBRO               1141
#define TRAINER_PIC_NEW_SKIER_GEN2               1142
#define TRAINER_PIC_NEW_SKIER               1143
#define TRAINER_PIC_NEW_SKIERF_GEN4DP               1144
#define TRAINER_PIC_NEW_SKIERF               1145
#define TRAINER_PIC_NEW_SKULLGRUNT               1146
#define TRAINER_PIC_NEW_SKULLGRUNTF               1147
#define TRAINER_PIC_NEW_SKYLA_MASTERS               1148
#define TRAINER_PIC_NEW_SKYLA_MASTERS2               1149
#define TRAINER_PIC_NEW_SKYLA               1150
#define TRAINER_PIC_NEW_SKYTRAINER               1151
#define TRAINER_PIC_NEW_SKYTRAINERF               1152
#define TRAINER_PIC_NEW_SMASHER               1153
#define TRAINER_PIC_NEW_SOLIERA               1154
#define TRAINER_PIC_NEW_SONIA_MASTERS               1155
#define TRAINER_PIC_NEW_SONIA_PROFESSOR               1156
#define TRAINER_PIC_NEW_SONIA               1157
#define TRAINER_PIC_NEW_SOPHOCLES               1158
#define TRAINER_PIC_NEW_SORDWARD_SHIELBERT               1159
#define TRAINER_PIC_NEW_SORDWARD               1160
#define TRAINER_PIC_NEW_SPENSER_GEN3               1161
#define TRAINER_PIC_NEW_SRANDJR_GEN3               1162
#define TRAINER_PIC_NEW_STARGRUNT_S               1163
#define TRAINER_PIC_NEW_STARGRUNT_V               1164
#define TRAINER_PIC_NEW_STARGRUNTF_S               1165
#define TRAINER_PIC_NEW_STARGRUNTF_V               1166
#define TRAINER_PIC_NEW_STEVEN_GEN3               1167
#define TRAINER_PIC_NEW_STEVEN_GEN6               1168
#define TRAINER_PIC_NEW_STEVEN_MASTERS               1169
#define TRAINER_PIC_NEW_STEVEN_MASTERS2               1170
#define TRAINER_PIC_NEW_STEVEN_MASTERS3               1171
#define TRAINER_PIC_NEW_STEVEN               1172
#define TRAINER_PIC_NEW_STREETTHUG_MASTERS               1173
#define TRAINER_PIC_NEW_STREETTHUG               1174
#define TRAINER_PIC_NEW_STRIKER               1175
#define TRAINER_PIC_NEW_SUPERNERD_GEN1               1176
#define TRAINER_PIC_NEW_SUPERNERD_GEN1RB               1177
#define TRAINER_PIC_NEW_SUPERNERD_GEN2               1178
#define TRAINER_PIC_NEW_SUPERNERD_GEN3               1179
#define TRAINER_PIC_NEW_SUPERNERD               1180
#define TRAINER_PIC_NEW_SURFER               1181
#define TRAINER_PIC_NEW_SWIMMER_GEN1               1182
#define TRAINER_PIC_NEW_SWIMMER_GEN1RB               1183
#define TRAINER_PIC_NEW_SWIMMER_GEN4               1184
#define TRAINER_PIC_NEW_SWIMMER_GEN4DP               1185
#define TRAINER_PIC_NEW_SWIMMER_GEN4JP               1186
#define TRAINER_PIC_NEW_SWIMMER_GEN6               1187
#define TRAINER_PIC_NEW_SWIMMER_GEN7               1188
#define TRAINER_PIC_NEW_SWIMMER_GEN8               1189
#define TRAINER_PIC_NEW_SWIMMER_MASTERS               1190
#define TRAINER_PIC_NEW_SWIMMER               1191
#define TRAINER_PIC_NEW_SWIMMERF_GEN2               1192
#define TRAINER_PIC_NEW_SWIMMERF_GEN3               1193
#define TRAINER_PIC_NEW_SWIMMERF_GEN3RS               1194
#define TRAINER_PIC_NEW_SWIMMERF_GEN4               1195
#define TRAINER_PIC_NEW_SWIMMERF_GEN4DP               1196
#define TRAINER_PIC_NEW_SWIMMERF_GEN6               1197
#define TRAINER_PIC_NEW_SWIMMERF_GEN7               1198
#define TRAINER_PIC_NEW_SWIMMERF_GEN8               1199
#define TRAINER_PIC_NEW_SWIMMERF               1200
#define TRAINER_PIC_NEW_SWIMMERF2_GEN6               1201
#define TRAINER_PIC_NEW_SWIMMERF2_GEN7               1202
#define TRAINER_PIC_NEW_SWIMMERFJP_GEN2               1203
#define TRAINER_PIC_NEW_SWIMMERM_GEN2               1204
#define TRAINER_PIC_NEW_SWIMMERM_GEN3               1205
#define TRAINER_PIC_NEW_SWIMMERM_GEN3RS               1206
#define TRAINER_PIC_NEW_SYCAMORE               1207
#define TRAINER_PIC_NEW_TABITHA_GEN3               1208
#define TRAINER_PIC_NEW_TAMER_GEN1               1209
#define TRAINER_PIC_NEW_TAMER_GEN1RB               1210
#define TRAINER_PIC_NEW_TAMER_GEN3               1211
#define TRAINER_PIC_NEW_TAOHUA               1212
#define TRAINER_PIC_NEW_TATE               1213
#define TRAINER_PIC_NEW_TATEANDLIZA_GEN3               1214
#define TRAINER_PIC_NEW_TATEANDLIZA_GEN6               1215
#define TRAINER_PIC_NEW_TEACHER_GEN2               1216
#define TRAINER_PIC_NEW_TEACHER_GEN7               1217
#define TRAINER_PIC_NEW_TEACHER               1218
#define TRAINER_PIC_NEW_TEAMAQUABETA_GEN3               1219
#define TRAINER_PIC_NEW_TEAMAQUAGRUNTF_GEN3               1220
#define TRAINER_PIC_NEW_TEAMAQUAGRUNTM_GEN3               1221
#define TRAINER_PIC_NEW_TEAMMAGMAGRUNTF_GEN3               1222
#define TRAINER_PIC_NEW_TEAMMAGMAGRUNTM_GEN3               1223
#define TRAINER_PIC_NEW_TEAMMATES               1224
#define TRAINER_PIC_NEW_TEAMROCKET               1225
#define TRAINER_PIC_NEW_TEAMROCKETGRUNTF_GEN3               1226
#define TRAINER_PIC_NEW_TEAMROCKETGRUNTM_GEN3               1227
#define TRAINER_PIC_NEW_THEROYAL               1228
#define TRAINER_PIC_NEW_THORTON               1229
#define TRAINER_PIC_NEW_TIERNO               1230
#define TRAINER_PIC_NEW_TOURIST               1231
#define TRAINER_PIC_NEW_TOURISTF               1232
#define TRAINER_PIC_NEW_TOURISTF2               1233
#define TRAINER_PIC_NEW_TRIALGUIDE               1234
#define TRAINER_PIC_NEW_TRIALGUIDEF               1235
#define TRAINER_PIC_NEW_TRIATHLETEBIKER_GEN6               1236
#define TRAINER_PIC_NEW_TRIATHLETEBIKERF_GEN3               1237
#define TRAINER_PIC_NEW_TRIATHLETEBIKERM_GEN3               1238
#define TRAINER_PIC_NEW_TRIATHLETERUNNER_GEN6               1239
#define TRAINER_PIC_NEW_TRIATHLETERUNNERF_GEN3               1240
#define TRAINER_PIC_NEW_TRIATHLETERUNNERM_GEN3               1241
#define TRAINER_PIC_NEW_TRIATHLETESWIMMER_GEN6               1242
#define TRAINER_PIC_NEW_TRIATHLETESWIMMERF_GEN3               1243
#define TRAINER_PIC_NEW_TRIATHLETESWIMMERM_GEN3               1244
#define TRAINER_PIC_NEW_TUBER_GEN3               1245
#define TRAINER_PIC_NEW_TUBER_GEN6               1246
#define TRAINER_PIC_NEW_TUBER               1247
#define TRAINER_PIC_NEW_TUBERF_GEN3               1248
#define TRAINER_PIC_NEW_TUBERF_GEN3RS               1249
#define TRAINER_PIC_NEW_TUBERF_GEN6               1250
#define TRAINER_PIC_NEW_TUBERF               1251
#define TRAINER_PIC_NEW_TUCKER_GEN3               1252
#define TRAINER_PIC_NEW_TULI               1253
#define TRAINER_PIC_NEW_TULIP               1254
#define TRAINER_PIC_NEW_TURO               1255
#define TRAINER_PIC_NEW_TWINS_GEN2               1256
#define TRAINER_PIC_NEW_TWINS_GEN3               1257
#define TRAINER_PIC_NEW_TWINS_GEN3RS               1258
#define TRAINER_PIC_NEW_TWINS_GEN4               1259
#define TRAINER_PIC_NEW_TWINS_GEN4DP               1260
#define TRAINER_PIC_NEW_TWINS_GEN6               1261
#define TRAINER_PIC_NEW_TWINS               1262
#define TRAINER_PIC_NEW_TYME               1263
#define TRAINER_PIC_NEW_ULTRAFORESTKARTENVOY               1264
#define TRAINER_PIC_NEW_UNKNOWN               1265
#define TRAINER_PIC_NEW_UNKNOWNF               1266
#define TRAINER_PIC_NEW_VALERIE               1267
#define TRAINER_PIC_NEW_VESSA               1268
#define TRAINER_PIC_NEW_VETERAN_GEN4               1269
#define TRAINER_PIC_NEW_VETERAN_GEN6               1270
#define TRAINER_PIC_NEW_VETERAN_GEN7               1271
#define TRAINER_PIC_NEW_VETERAN               1272
#define TRAINER_PIC_NEW_VETERANF_GEN6               1273
#define TRAINER_PIC_NEW_VETERANF_GEN7               1274
#define TRAINER_PIC_NEW_VETERANF               1275
#define TRAINER_PIC_NEW_VICTOR_DOJO               1276
#define TRAINER_PIC_NEW_VICTOR               1277
#define TRAINER_PIC_NEW_VIOLA               1278
#define TRAINER_PIC_NEW_VOLKNER_MASTERS               1279
#define TRAINER_PIC_NEW_VOLKNER               1280
#define TRAINER_PIC_NEW_VOLO_GINKGO               1281
#define TRAINER_PIC_NEW_VOLO               1282
#define TRAINER_PIC_NEW_WAITER_GEN4               1283
#define TRAINER_PIC_NEW_WAITER_GEN4DP               1284
#define TRAINER_PIC_NEW_WAITER               1285
#define TRAINER_PIC_NEW_WAITRESS_GEN4               1286
#define TRAINER_PIC_NEW_WAITRESS_GEN6               1287
#define TRAINER_PIC_NEW_WAITRESS               1288
#define TRAINER_PIC_NEW_WALLACE_GEN3               1289
#define TRAINER_PIC_NEW_WALLACE_GEN3RS               1290
#define TRAINER_PIC_NEW_WALLACE_GEN6               1291
#define TRAINER_PIC_NEW_WALLACE               1292
#define TRAINER_PIC_NEW_WALLY_GEN3               1293
#define TRAINER_PIC_NEW_WALLY_MASTERS               1294
#define TRAINER_PIC_NEW_WALLY               1295
#define TRAINER_PIC_NEW_WATTSON_GEN3               1296
#define TRAINER_PIC_NEW_WATTSON               1297
#define TRAINER_PIC_NEW_WHITNEY_GEN2               1298
#define TRAINER_PIC_NEW_WHITNEY               1299
#define TRAINER_PIC_NEW_WICKE               1300
#define TRAINER_PIC_NEW_WIKSTROM               1301
#define TRAINER_PIC_NEW_WILL_GEN2               1302
#define TRAINER_PIC_NEW_WILL               1303
#define TRAINER_PIC_NEW_WINONA_GEN3               1304
#define TRAINER_PIC_NEW_WINONA_GEN6               1305
#define TRAINER_PIC_NEW_WINONA               1306
#define TRAINER_PIC_NEW_WORKER_GEN4               1307
#define TRAINER_PIC_NEW_WORKER_GEN6               1308
#define TRAINER_PIC_NEW_WORKER_GEN7               1309
#define TRAINER_PIC_NEW_WORKER_GEN8               1310
#define TRAINER_PIC_NEW_WORKER_LGPE               1311
#define TRAINER_PIC_NEW_WORKER               1312
#define TRAINER_PIC_NEW_WORKER2_GEN6               1313
#define TRAINER_PIC_NEW_WORKERF_GEN8               1314
#define TRAINER_PIC_NEW_WORKERICE               1315
#define TRAINER_PIC_NEW_WULFRIC               1316
#define TRAINER_PIC_NEW_XEROSIC               1317
#define TRAINER_PIC_NEW_YELLGRUNT               1318
#define TRAINER_PIC_NEW_YELLGRUNTF               1319
#define TRAINER_PIC_NEW_YELLOW               1320
#define TRAINER_PIC_NEW_YOUNGATHLETE               1321
#define TRAINER_PIC_NEW_YOUNGATHLETEF               1322
#define TRAINER_PIC_NEW_YOUNGCOUPLE_GEN3               1323
#define TRAINER_PIC_NEW_YOUNGCOUPLE_GEN3RS               1324
#define TRAINER_PIC_NEW_YOUNGCOUPLE_GEN4DP               1325
#define TRAINER_PIC_NEW_YOUNGCOUPLE_GEN6               1326
#define TRAINER_PIC_NEW_YOUNGCOUPLE               1327
#define TRAINER_PIC_NEW_YOUNGN               1328
#define TRAINER_PIC_NEW_YOUNGSTER_GEN1               1329
#define TRAINER_PIC_NEW_YOUNGSTER_GEN1RB               1330
#define TRAINER_PIC_NEW_YOUNGSTER_GEN2               1331
#define TRAINER_PIC_NEW_YOUNGSTER_GEN3               1332
#define TRAINER_PIC_NEW_YOUNGSTER_GEN3RS               1333
#define TRAINER_PIC_NEW_YOUNGSTER_GEN4               1334
#define TRAINER_PIC_NEW_YOUNGSTER_GEN4DP               1335
#define TRAINER_PIC_NEW_YOUNGSTER_GEN6               1336
#define TRAINER_PIC_NEW_YOUNGSTER_GEN6XY               1337
#define TRAINER_PIC_NEW_YOUNGSTER_GEN7               1338
#define TRAINER_PIC_NEW_YOUNGSTER_GEN8               1339
#define TRAINER_PIC_NEW_YOUNGSTER_MASTERS               1340
#define TRAINER_PIC_NEW_YOUNGSTER               1341
#define TRAINER_PIC_NEW_ZINNIA               1342
#define TRAINER_PIC_NEW_ZINZOLIN               1343
#define TRAINER_PIC_NEW_ZISU               1344
#define TRAINER_PIC_NEW_ZOSSIE               1345

// The player back pics are assumed to alternate according to the gender values (MALE/FEMALE)
#define TRAINER_BACK_PIC_RED                    0
#define TRAINER_BACK_PIC_LEAF                   1
#define TRAINER_BACK_PIC_RUBY_SAPPHIRE_BRENDAN  2
#define TRAINER_BACK_PIC_RUBY_SAPPHIRE_MAY      3
#define TRAINER_BACK_PIC_POKEDUDE               4
#define TRAINER_BACK_PIC_OLD_MAN                5

// Special Trainer Ids.
#define TRAINER_UNION_ROOM          0xC00
#define TRAINER_LINK_OPPONENT       0x800
#define TRAINER_SECRET_BASE         0x400

#define TRAINER_CLASS_NONE                0
#define TRAINER_CLASS_PKMN_TRAINER_UNUSED 1
#define TRAINER_CLASS_AQUA_LEADER         2
#define TRAINER_CLASS_TEAM_AQUA           3
#define TRAINER_CLASS_RS_AROMA_LADY       4
#define TRAINER_CLASS_RS_RUIN_MANIAC      5
#define TRAINER_CLASS_INTERVIEWER         6
#define TRAINER_CLASS_RS_TUBER_F          7
#define TRAINER_CLASS_RS_TUBER_M          8
#define TRAINER_CLASS_RS_COOLTRAINER      9
#define TRAINER_CLASS_HEX_MANIAC          10
#define TRAINER_CLASS_RS_LADY             11
#define TRAINER_CLASS_RS_BEAUTY           12
#define TRAINER_CLASS_RICH_BOY            13
#define TRAINER_CLASS_RS_POKEMANIAC       14
#define TRAINER_CLASS_RS_SWIMMER_M        15
#define TRAINER_CLASS_RS_BLACK_BELT       16
#define TRAINER_CLASS_GUITARIST           17
#define TRAINER_CLASS_KINDLER             18
#define TRAINER_CLASS_RS_CAMPER           19
#define TRAINER_CLASS_BUG_MANIAC          20
#define TRAINER_CLASS_RS_PSYCHIC          21
#define TRAINER_CLASS_RS_GENTLEMAN        22
#define TRAINER_CLASS_RS_ELITE_FOUR       23
#define TRAINER_CLASS_RS_LEADER           24
#define TRAINER_CLASS_SCHOOL_KID          25
#define TRAINER_CLASS_SR_AND_JR           26
#define TRAINER_CLASS_POKEFAN             27
#define TRAINER_CLASS_EXPERT              28
#define TRAINER_CLASS_RS_YOUNGSTER        29
#define TRAINER_CLASS_RS_CHAMPION         30
#define TRAINER_CLASS_RS_FISHERMAN        31
#define TRAINER_CLASS_TRIATHLETE          32
#define TRAINER_CLASS_DRAGON_TAMER        33
#define TRAINER_CLASS_RS_BIRD_KEEPER      34
#define TRAINER_CLASS_NINJA_BOY           35
#define TRAINER_CLASS_BATTLE_GIRL         36
#define TRAINER_CLASS_PARASOL_LADY        37
#define TRAINER_CLASS_RS_SWIMMER_F        38
#define TRAINER_CLASS_RS_PICNICKER        39
#define TRAINER_CLASS_RS_TWINS            40
#define TRAINER_CLASS_RS_SAILOR           41
#define TRAINER_CLASS_BOARDER             42
#define TRAINER_CLASS_COLLECTOR           43
#define TRAINER_CLASS_PKMN_TRAINER        44
#define TRAINER_CLASS_RS_PKMN_BREEDER     45
#define TRAINER_CLASS_RS_PKMN_RANGER      46
#define TRAINER_CLASS_MAGMA_LEADER        47
#define TRAINER_CLASS_TEAM_MAGMA          48
#define TRAINER_CLASS_RS_LASS             49
#define TRAINER_CLASS_RS_BUG_CATCHER      50
#define TRAINER_CLASS_RS_HIKER            51
#define TRAINER_CLASS_RS_YOUNG_COUPLE     52
#define TRAINER_CLASS_OLD_COUPLE          53
#define TRAINER_CLASS_RS_SIS_AND_BRO      54
#define TRAINER_CLASS_AQUA_ADMIN          55
#define TRAINER_CLASS_MAGMA_ADMIN         56
#define TRAINER_CLASS_YOUNGSTER           57
#define TRAINER_CLASS_BUG_CATCHER         58
#define TRAINER_CLASS_LASS                59
#define TRAINER_CLASS_SAILOR              60
#define TRAINER_CLASS_CAMPER              61
#define TRAINER_CLASS_PICNICKER           62
#define TRAINER_CLASS_POKEMANIAC          63
#define TRAINER_CLASS_SUPER_NERD          64
#define TRAINER_CLASS_HIKER               65
#define TRAINER_CLASS_BIKER               66
#define TRAINER_CLASS_BURGLAR             67
#define TRAINER_CLASS_ENGINEER            68
#define TRAINER_CLASS_FISHERMAN           69
#define TRAINER_CLASS_SWIMMER_M           70
#define TRAINER_CLASS_CUE_BALL            71
#define TRAINER_CLASS_GAMER               72
#define TRAINER_CLASS_BEAUTY              73
#define TRAINER_CLASS_SWIMMER_F           74
#define TRAINER_CLASS_PSYCHIC             75
#define TRAINER_CLASS_ROCKER              76
#define TRAINER_CLASS_JUGGLER             77
#define TRAINER_CLASS_TAMER               78
#define TRAINER_CLASS_BIRD_KEEPER         79
#define TRAINER_CLASS_BLACK_BELT          80
#define TRAINER_CLASS_RIVAL_EARLY         81
#define TRAINER_CLASS_SCIENTIST           82
#define TRAINER_CLASS_BOSS                83
#define TRAINER_CLASS_LEADER              84
#define TRAINER_CLASS_TEAM_ROCKET         85
#define TRAINER_CLASS_COOLTRAINER         86
#define TRAINER_CLASS_ELITE_FOUR          87
#define TRAINER_CLASS_GENTLEMAN           88
#define TRAINER_CLASS_RIVAL_LATE          89
#define TRAINER_CLASS_CHAMPION            90
#define TRAINER_CLASS_CHANNELER           91
#define TRAINER_CLASS_TWINS               92
#define TRAINER_CLASS_COOL_COUPLE         93
#define TRAINER_CLASS_YOUNG_COUPLE        94
#define TRAINER_CLASS_CRUSH_KIN           95
#define TRAINER_CLASS_SIS_AND_BRO         96
#define TRAINER_CLASS_PKMN_PROF           97
#define TRAINER_CLASS_PLAYER              98
#define TRAINER_CLASS_CRUSH_GIRL          99
#define TRAINER_CLASS_TUBER               100
#define TRAINER_CLASS_PKMN_BREEDER        101
#define TRAINER_CLASS_PKMN_RANGER         102
#define TRAINER_CLASS_AROMA_LADY          103
#define TRAINER_CLASS_RUIN_MANIAC         104
#define TRAINER_CLASS_LADY                105
#define TRAINER_CLASS_PAINTER             106

#define FACILITY_CLASS_AQUA_LEADER_ARCHIE     0
#define FACILITY_CLASS_AQUA_GRUNT_M           1
#define FACILITY_CLASS_AQUA_GRUNT_F           2
#define FACILITY_CLASS_RS_AROMA_LADY          3
#define FACILITY_CLASS_RS_RUIN_MANIAC         4
#define FACILITY_CLASS_INTERVIEWER            5
#define FACILITY_CLASS_RS_TUBER_F             6
#define FACILITY_CLASS_RS_TUBER_M             7
#define FACILITY_CLASS_RS_COOLTRAINER_M       8
#define FACILITY_CLASS_RS_COOLTRAINER_F       9
#define FACILITY_CLASS_HEX_MANIAC             10
#define FACILITY_CLASS_RS_LADY                11
#define FACILITY_CLASS_RS_BEAUTY              12
#define FACILITY_CLASS_RICH_BOY               13
#define FACILITY_CLASS_RS_POKEMANIAC          14
#define FACILITY_CLASS_RS_SWIMMER_M           15
#define FACILITY_CLASS_RS_BLACK_BELT          16
#define FACILITY_CLASS_GUITARIST              17
#define FACILITY_CLASS_KINDLER                18
#define FACILITY_CLASS_RS_CAMPER              19
#define FACILITY_CLASS_BUG_MANIAC             20
#define FACILITY_CLASS_RS_PSYCHIC_M           21
#define FACILITY_CLASS_RS_PSYCHIC_F           22
#define FACILITY_CLASS_RS_GENTLEMAN           23
#define FACILITY_CLASS_ELITE_FOUR_SIDNEY      24
#define FACILITY_CLASS_ELITE_FOUR_PHOEBE      25
#define FACILITY_CLASS_LEADER_ROXANNE         26
#define FACILITY_CLASS_LEADER_BRAWLY          27
#define FACILITY_CLASS_LEADER_TATE_AND_LIZA   28
#define FACILITY_CLASS_SCHOOL_KID_M           29
#define FACILITY_CLASS_SCHOOL_KID_F           30
#define FACILITY_CLASS_SR_AND_JR              31
#define FACILITY_CLASS_POKEFAN_M              32
#define FACILITY_CLASS_POKEFAN_F              33
#define FACILITY_CLASS_EXPERT_M               34
#define FACILITY_CLASS_EXPERT_F               35
#define FACILITY_CLASS_RS_YOUNGSTER           36
#define FACILITY_CLASS_CHAMPION_STEVEN        37
#define FACILITY_CLASS_RS_FISHERMAN           38
#define FACILITY_CLASS_CYCLING_TRIATHLETE_M   39
#define FACILITY_CLASS_CYCLING_TRIATHLETE_F   40
#define FACILITY_CLASS_RUNNING_TRIATHLETE_M   41
#define FACILITY_CLASS_RUNNING_TRIATHLETE_F   42
#define FACILITY_CLASS_SWIMMING_TRIATHLETE_M  43
#define FACILITY_CLASS_SWIMMING_TRIATHLETE_F  44
#define FACILITY_CLASS_DRAGON_TAMER           45
#define FACILITY_CLASS_RS_BIRD_KEEPER         46
#define FACILITY_CLASS_NINJA_BOY              47
#define FACILITY_CLASS_BATTLE_GIRL            48
#define FACILITY_CLASS_PARASOL_LADY           49
#define FACILITY_CLASS_RS_SWIMMER_F           50
#define FACILITY_CLASS_RS_PICNICKER           51
#define FACILITY_CLASS_RS_TWINS               52
#define FACILITY_CLASS_RS_SAILOR              53
#define FACILITY_CLASS_BOARDER_M              54
#define FACILITY_CLASS_BOARDER_F              55
#define FACILITY_CLASS_COLLECTOR              56
#define FACILITY_CLASS_PKMN_TRAINER_WALLY     57
#define FACILITY_CLASS_PKMN_TRAINER_BRENDAN   58
#define FACILITY_CLASS_PKMN_TRAINER_BRENDAN_2 59
#define FACILITY_CLASS_PKMN_TRAINER_BRENDAN_3 60
#define FACILITY_CLASS_PKMN_TRAINER_MAY       61
#define FACILITY_CLASS_PKMN_TRAINER_MAY_2     62
#define FACILITY_CLASS_PKMN_TRAINER_MAY_3     63
#define FACILITY_CLASS_RS_PKMN_BREEDER_M      64
#define FACILITY_CLASS_RS_PKMN_BREEDER_F      65
#define FACILITY_CLASS_RS_PKMN_RANGER_M       66
#define FACILITY_CLASS_RS_PKMN_RANGER_F       67
#define FACILITY_CLASS_MAGMA_LEADER_MAXIE     68
#define FACILITY_CLASS_MAGMA_GRUNT_M          69
#define FACILITY_CLASS_MAGMA_GRUNT_F          70
#define FACILITY_CLASS_RS_LASS                71
#define FACILITY_CLASS_RS_BUG_CATCHER         72
#define FACILITY_CLASS_RS_HIKER               73
#define FACILITY_CLASS_RS_YOUNG_COUPLE        74
#define FACILITY_CLASS_OLD_COUPLE             75
#define FACILITY_CLASS_RS_SIS_AND_BRO         76
#define FACILITY_CLASS_AQUA_ADMIN_M           77
#define FACILITY_CLASS_AQUA_ADMIN_F           78
#define FACILITY_CLASS_MAGMA_ADMIN_M          79
#define FACILITY_CLASS_MAGMA_ADMIN_F          80
#define FACILITY_CLASS_LEADER_WATTSON         81
#define FACILITY_CLASS_LEADER_FLANNERY        82
#define FACILITY_CLASS_LEADER_NORMAN          83
#define FACILITY_CLASS_LEADER_WINONA          84
#define FACILITY_CLASS_LEADER_WALLACE         85
#define FACILITY_CLASS_ELITE_FOUR_GLACIA      86
#define FACILITY_CLASS_ELITE_FOUR_DRAKE       87
#define FACILITY_CLASS_YOUNGSTER              88
#define FACILITY_CLASS_BUG_CATCHER            89
#define FACILITY_CLASS_LASS                   90
#define FACILITY_CLASS_SAILOR                 91
#define FACILITY_CLASS_CAMPER                 92
#define FACILITY_CLASS_PICNICKER              93
#define FACILITY_CLASS_POKEMANIAC             94
#define FACILITY_CLASS_SUPER_NERD             95
#define FACILITY_CLASS_HIKER                  96
#define FACILITY_CLASS_BIKER                  97
#define FACILITY_CLASS_BURGLAR                98
#define FACILITY_CLASS_ENGINEER               99
#define FACILITY_CLASS_FISHERMAN              100
#define FACILITY_CLASS_SWIMMER_M              101
#define FACILITY_CLASS_CUE_BALL               102
#define FACILITY_CLASS_GAMER                  103
#define FACILITY_CLASS_BEAUTY                 104
#define FACILITY_CLASS_SWIMMER_F              105
#define FACILITY_CLASS_PSYCHIC_M              106
#define FACILITY_CLASS_ROCKER                 107
#define FACILITY_CLASS_JUGGLER                108
#define FACILITY_CLASS_TAMER                  109
#define FACILITY_CLASS_BIRD_KEEPER            110
#define FACILITY_CLASS_BLACK_BELT             111
#define FACILITY_CLASS_RIVAL_EARLY            112
#define FACILITY_CLASS_SCIENTIST              113
#define FACILITY_CLASS_BOSS                   114
#define FACILITY_CLASS_ROCKET_GRUNT_M         115
#define FACILITY_CLASS_COOLTRAINER_M          116
#define FACILITY_CLASS_COOLTRAINER_F          117
#define FACILITY_CLASS_ELITE_FOUR_LORELEI     118
#define FACILITY_CLASS_ELITE_FOUR_BRUNO       119
#define FACILITY_CLASS_LEADER_M               120
#define FACILITY_CLASS_LEADER_F               121
#define FACILITY_CLASS_GENTLEMAN              122
#define FACILITY_CLASS_RIVAL_LATE             123
#define FACILITY_CLASS_CHAMPION_RIVAL         124
#define FACILITY_CLASS_CHANNELER              125
#define FACILITY_CLASS_TWINS                  126
#define FACILITY_CLASS_COOL_COUPLE            127
#define FACILITY_CLASS_YOUNG_COUPLE           128
#define FACILITY_CLASS_CRUSH_KIN              129
#define FACILITY_CLASS_SIS_AND_BRO            130
#define FACILITY_CLASS_PKMN_PROF              131
#define FACILITY_CLASS_BRENDAN                132
#define FACILITY_CLASS_MAY                    133
#define FACILITY_CLASS_RED                    134
#define FACILITY_CLASS_LEAF                   135
#define FACILITY_CLASS_ROCKET_GRUNT_F         136
#define FACILITY_CLASS_PSYCHIC_F              137
#define FACILITY_CLASS_CRUSH_GIRL             138
#define FACILITY_CLASS_TUBER                  139
#define FACILITY_CLASS_PKMN_BREEDER           140
#define FACILITY_CLASS_PKMN_RANGER_M          141
#define FACILITY_CLASS_PKMN_RANGER_F          142
#define FACILITY_CLASS_AROMA_LADY             143
#define FACILITY_CLASS_RUIN_MANIAC            144
#define FACILITY_CLASS_LADY                   145
#define FACILITY_CLASS_PAINTER                146
#define FACILITY_CLASS_ELITE_FOUR_AGATHA      147
#define FACILITY_CLASS_ELITE_FOUR_LANCE       148
#define FACILITY_CLASS_CHAMPION_RIVAL_2       149

#define F_TRAINER_FEMALE (1 << 7)

// All trainer parties specify the IV, level, and species for each Pokémon in the
// party. Some trainer parties also specify held items and custom moves for each
// Pokémon.
#define F_TRAINER_PARTY_CUSTOM_MOVESET (1 << 0)
#define F_TRAINER_PARTY_HELD_ITEM      (1 << 1)

#endif  // GUARD_CONSTANTS_TRAINERS_H
